[package]
name = "risingwave_expr"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "0.7"
anyhow = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
chrono-tz = { version = "0.7", features = ["case-insensitive"] }
dyn-clone = "1"
either = "1"
itertools = "0.10"
md5 = "0.7.0"
num-traits = "0.2"
ouroboros = "0.15"
parse-display = "0.6"
paste = "1"
prost = "0.11"
regex = "1"
risingwave_common = { path = "../common" }
risingwave_pb = { path = "../prost" }
rust_decimal = "1"
speedate = "0.7.0"
thiserror = "1"
toml = "0.5"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "expr"
harness = false
