disallowed-methods = [
    { path = "risingwave_common::error::internal_err", reason = "Please use per-crate error type instead." },
    { path = "risingwave_common::error::internal_error", reason = "Please use per-crate error type instead." },
    { path = "risingwave_common::error::tonic_err", reason = "Please use per-crate error type instead." },
]

disallowed-types = [
    { path = "risingwave_common::error::ErrorCode", reason = "Please use per-crate error type instead." },
    { path = "risingwave_common::error::RwError", reason = "Please use per-crate error type instead." },
    { path = "risingwave_common::error::Result", reason = "Please use per-crate error type instead." },
    { path = "risingwave_common::error::ToRwResult", reason = "Please use per-crate error type instead." },
    { path = "risingwave_common::error::ToErrorStr", reason = "Please use per-crate error type instead." },
]

doc-valid-idents = [
    "RisingWave",
    "MinIO",
    "ProtoBuf",
    "BloomFilter",
    "gRPC",
    "PostgreSQL",
    "MySQL",
    "TopN",
    "VNode"
]
avoid-breaking-exported-api = false
upper-case-acronyms-aggressive = true
too-many-arguments-threshold = 10
