disallowed-methods = [
    { path = "risingwave_common::error::internal_err", reason = "Please use per-crate error type instead." },
    { path = "risingwave_common::error::internal_error", reason = "Please use per-crate error type instead." },
    { path = "risingwave_common::error::tonic_err", reason = "Please use per-crate error type instead." },
]

disallowed-types = [
    { path = "risingwave_common::error::ErrorCode", reason = "Please use per-crate error type instead." },
    { path = "risingwave_common::error::RwError", reason = "Please use per-crate error type instead." },
    { path = "risingwave_common::error::Result", reason = "Please use per-crate error type instead." },
    { path = "risingwave_common::error::ToRwResult", reason = "Please use per-crate error type instead." },
    { path = "risingwave_common::error::ToErrorStr", reason = "Please use per-crate error type instead." },
]
