[package]
name = "risingwave_meta"
version = "0.1.3"
edition = "2021"

[dependencies]
anyhow = "1"
async-recursion = "1"
async-stream = "0.3"
async-trait = "0.1"
axum = "0.4"
byteorder = "1"
bytes = { version = "1", features = ["serde"] }
chrono = "0.4"
clap = { version = "3", features = ["derive"] }
crc32fast = "1"
either = "1"
etcd-client = "0.8"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hex = "0.4"
hyper = "0.14"
itertools = "0.10"
lazy_static = "1"
log = "0.4"
memcomparable = { path = "../utils/memcomparable" }
moka = { version = "0.7", features = ["future"] }
num-integer = "0.1"
num-traits = "0.2"
parking_lot = { version = "0.12", features = ["arc_lock"] }
paste = "1"
prometheus = "0.13"
prost = "0.9"
risingwave_common = { path = "../common" }
risingwave_connector = { path = "../connector" }
risingwave_pb = { path = "../prost" }
risingwave_rpc_client = { path = "../rpc_client" }
risingwave_storage = { path = "../storage" }
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
smallvec = "1"
thiserror = "1"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-retry = "0.3"
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.6"
tower = { version = "0.4", features = ["util", "load-shed"] }
tower-http = { version = "0.2", features = ["add-extension", "cors", "fs"] }
tracing = { version = "0.1" }
uuid = { version = "0.8", features = ["v4"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1"
rand = "0.8"
tempfile = "3"

[features]
default = ["blockv2"]
blockv2 = ["risingwave_storage/blockv2"]
