# configs for the dedicated MariaDB connector
connector.class=io.debezium.connector.mariadb.MariaDbConnector
snapshot.mode=${debezium.snapshot.mode:-initial}
database.hostname=${hostname}
database.port=${port}
database.user=${username}
database.password=${password}
database.include.list=${database.name}
table.include.list=${database.name}.${table.name:-*}
schema.history.internal.store.only.captured.tables.ddl=true
schema.history.internal.store.only.captured.databases.ddl=true

schema.history.internal=com.risingwave.connector.cdc.debezium.internal.OpendalSchemaHistory
snapshot.mode.custom.name=no_data_recovery

include.schema.changes=${auto.schema.change:-false}
database.server.id=${server.id}
database.ssl.mode=${ssl.mode:-disable}
heartbeat.interval.ms=${debezium.heartbeat.interval.ms:-60000}
name=${hostname}:${port}:${database.name}.${table.name:-RW_CDC_Sharing}
provide.transaction.metadata=${transactional:-false}
