version: 2
updates:
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  # Disable auto rebase to reduce cost. Use `@dependabot rebase` manually instead.
  rebase-strategy: "disabled"

  # Create a group of dependencies to be updated together in one pull request
  groups:
    arrow:
      patterns:
        - "arrow*"
    aws:
      patterns:
        - "aws*"
    # a grouped PR for any dependencies where the highest resolvable version is a patch or minor SemVer update
    non-major-versions:
      update-types:
        - "minor"
        - "patch"