version: 2
updates:
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  # Disable auto rebase to reduce cost. Use `@dependabot rebase` manually instead.
  rebase-strategy: "disabled"
