version: 1
labels:
- label: "type/feature"
  title: "^feat*"
- label: "type/fix"
  title: "^fix*"
- label: "component/test"
  title: "^test*"
- label: "type/refactor"
  title: "^refactor*"
- label: "type/style"
  title: "^style*"
- label: "type/chore"
  title: "^chore*"
- label: "component/doc"
  title: "^doc*"
