[package]
name = "nexmark"
version = "0.1.0"
edition = "2021"
description = "Nexmark data stream generator."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
rand = { version = "0.8", features = ["small_rng"] }
serde = { version = "1", features = ["derive"], optional = true }
