header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Singularity Data

  paths:
    - "src/**/*.rs"
    - "dashboard/**/*.js"
    - "dashboard/**/*.ts"
    - "src/**/*.html"

  paths-ignore:
    - "**/gen/**"
    - "**/*.d.ts"
    - "src/sqlparser/**/*.rs"

  comment: on-failure
