header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Singularity Data

  paths:
    - 'rust/**/*.rs'
    # - 'legacy/**/*.java'
    # - 'legacy/**/*.kt'
    - 'dashboard/**/*.js'
    - 'rust/**/*.html'

  comment: on-failure
