queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "base=main"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "check-success=buildkite/pull-request"
      - "check-success=buildkite/docker"
      - "check-success=license/cla"
      - "check-success=task-list-completed"
    actions:
      queue:
        name: default
        method: squash
