#!/bin/bash

if [ -z "$(which cargo-make)" ]; then
    echo "Installing cargo-make..."
    cargo install cargo-make --version "^0.35"
fi

if [ $# -eq 0 ]; then
    cargo make --list-all-steps
    exit 0
fi

touch riselab-components.user.env
cargo make configure-if-not-configured
cargo make "$@"
