default-v6:
  steps:
    - use: meta-node
      address: "[::1]"
      listen-address: "[::]"
    - use: compute-node
      address: "[::1]"
      listen-address: "[::]"
    - use: frontend
      address: "[::1]"
      listen-address: "[::]"
