# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . /app

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variables
ENV MONGO_HOST mongodb
ENV MONGO_PORT 27017
ENV MONGO_DB_NAME random_data

# Run app.py when the container launches
CMD ["python", "app.py"]
