// Copyright 2025 RisingWave Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Ported from https://github.com/MrFriendly-B-V/tracing-slf4j,
// which is licensed under the Apache License, Version 2.0.

package com.risingwave.tracing;

// Import log4j's ParameterizedMessage, so that we can format the messages
// with the same interpolation as log4j (i.e. "{}" instead of "%s").
import org.apache.commons.lang3.exception.ExceptionUtils;
import org.apache.logging.log4j.message.ParameterizedMessage;
import org.slf4j.Marker;
import org.slf4j.event.Level;
import org.slf4j.helpers.LegacyAbstractLogger;

public class TracingSlf4jAdapter extends LegacyAbstractLogger {

    private final String name;

    public TracingSlf4jAdapter(String name) {
        this.name = name;
    }

    @Override
    public boolean isTraceEnabled() {
        return TracingSlf4jImpl.isEnabled(Level.TRACE);
    }

    @Override
    public boolean isDebugEnabled() {
        return TracingSlf4jImpl.isEnabled(Level.DEBUG);
    }

    @Override
    public boolean isInfoEnabled() {
        return TracingSlf4jImpl.isEnabled(Level.INFO);
    }

    @Override
    public boolean isWarnEnabled() {
        return TracingSlf4jImpl.isEnabled(Level.WARN);
    }

    @Override
    public boolean isErrorEnabled() {
        return TracingSlf4jImpl.isEnabled(Level.ERROR);
    }

    @Override
    protected String getFullyQualifiedCallerName() {
        return null;
    }

    @Override
    protected void handleNormalizedLoggingCall(
            Level level,
            Marker marker,
            String messagePattern,
            Object[] arguments,
            Throwable throwable) {
        // Filter out noisy Debezium TypeRegistry warnings like:
        // "Type [oid:13618, name:_pg_user_mappings] is already mapped"
        // They are harmless (caused by duplicate type registrations) but very verbose in logs.
        // Performance: Most logs fail the first check (level != WARN), so overhead is minimal.
        // For TypeRegistry WARN logs, we avoid expensive message formatting and JNI calls.
        if (level == Level.WARN
                && name != null
                && name.equals("io.debezium.connector.postgresql.TypeRegistry")
                && messagePattern != null
                && messagePattern.contains("is already mapped")) {
            return;
        }

        // Filter out Debezium PostgresDefaultValueConverter warnings for function call default
        // values.
        // These warnings occur when Debezium cannot parse function call expressions (e.g.,
        // "schema".function())
        // as constant values. This is expected behavior and does not affect CDC functionality.
        // The actual default values are generated by PostgreSQL during INSERT operations.
        if (level == Level.WARN
                && name != null
                && name.equals(
                        "io.debezium.connector.postgresql.connection.PostgresDefaultValueConverter")
                && messagePattern != null
                && messagePattern.contains("Cannot parse column default value")
                && messagePattern.contains("Expression evaluation is not supported")) {
            return;
        }
        var pm = new ParameterizedMessage(messagePattern, arguments, throwable);
        var message = pm.getFormattedMessage();

        String stackTrace = null;
        if (throwable != null) {
            stackTrace = ExceptionUtils.getStackTrace(throwable);
        }

        TracingSlf4jImpl.event(name, level, message, stackTrace);
    }
}
