[package]
name = "sqlparser_bench"
version = "0.1.0"
authors = ["Dandandan <danielheres@gmail.com>"]
edition = "2018"

[package.metadata.cargo-machete]
ignored = ["workspace-config", "workspace-hack", "task_stats_alloc"]

[dependencies]
risingwave_sqlparser = { path = "../" }

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "sqlparser_bench"
harness = false
