[package]
name = "risingwave_udf"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# need this latest PR: https://github.com/apache/arrow-rs/pull/3391
arrow-array = { git = "https://github.com/apache/arrow-rs", rev = "6139d898" }
arrow-flight = { git = "https://github.com/apache/arrow-rs", rev = "6139d898" }
arrow-schema = { git = "https://github.com/apache/arrow-rs", rev = "6139d898" }
futures-util = "0.3.25"
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = ["rt", "macros"] }
tonic = { version = "0.2", package = "madsim-tonic" }
