[package]
name = "with_options_build"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
syn = { version = "1", features = ["full"] }
walkdir = "2"

[lib]

[dev-dependencies]

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[lints]
workspace = true
