// Copyright 2022 Singularity Data
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#![allow(dead_code)]

use std::sync::Arc;

use bytes::Bytes;
use itertools::Itertools;
use risingwave_common::config::StorageConfig;
use risingwave_hummock_sdk::key::key_with_epoch;
use risingwave_meta::hummock::test_utils::setup_compute_env;
use risingwave_meta::hummock::MockHummockMetaClient;

use super::{CompressionAlgorithm, SstableMeta, DEFAULT_RESTART_INTERVAL};
use crate::hummock::iterator::test_utils::mock_sstable_store;
use crate::hummock::local_version_manager::LocalVersionManager;
use crate::hummock::value::HummockValue;
use crate::hummock::{
    CachePolicy, HummockStorage, SSTableBuilder, SSTableBuilderOptions, Sstable, SstableStoreRef,
};
use crate::monitor::StateStoreMetrics;

pub fn default_config_for_test() -> StorageConfig {
    StorageConfig {
        sstable_size: 256 * (1 << 20),
        block_size: 64 * (1 << 10),
        bloom_false_positive: 0.1,
        share_buffers_sync_parallelism: 2,
        data_directory: "hummock_001".to_string(),
        async_checkpoint_enabled: true,
        write_conflict_detection_enabled: true,
        block_cache_capacity: 64 << 20,
        meta_cache_capacity: 64 << 20,
    }
}

pub async fn mock_hummock_storage() -> HummockStorage {
    let (_env, hummock_manager_ref, _cluster_manager_ref, worker_node) =
        setup_compute_env(8080).await;
    let mock_hummock_meta_client = Arc::new(MockHummockMetaClient::new(
        hummock_manager_ref.clone(),
        worker_node.id,
    ));
    let sstable_store = mock_sstable_store();
    HummockStorage::with_default_stats(
        Arc::new(StorageConfig::default()),
        sstable_store.clone(),
        Arc::new(LocalVersionManager::new(sstable_store.clone())),
        mock_hummock_meta_client,
        Arc::new(StateStoreMetrics::unused()),
    )
    .await
    .unwrap()
}

/// Number of keys in table generated in `generate_table`.
pub const TEST_KEYS_COUNT: usize = 10000;

pub fn default_builder_opt_for_test() -> SSTableBuilderOptions {
    SSTableBuilderOptions {
        capacity: 256 * (1 << 20), // 256MB
        block_capacity: 4096,      // 4KB
        restart_interval: DEFAULT_RESTART_INTERVAL,
        bloom_false_positive: 0.1,
        compression_algorithm: CompressionAlgorithm::None,
    }
}

/// Generates sstable data and metadata from given `kv_iter`
pub fn gen_test_sstable_data(
    opts: SSTableBuilderOptions,
    kv_iter: impl Iterator<Item = (Vec<u8>, HummockValue<Vec<u8>>)>,
) -> (Bytes, SstableMeta) {
    let mut b = SSTableBuilder::new(opts);
    for (key, value) in kv_iter {
        b.add(&key, value.as_slice())
    }
    b.finish()
}

/// Generates a test table from the given `kv_iter` and put the kv value to `sstable_store`
pub async fn gen_test_sstable(
    opts: SSTableBuilderOptions,
    sst_id: u64,
    kv_iter: impl Iterator<Item = (Vec<u8>, HummockValue<Vec<u8>>)>,
    sstable_store: SstableStoreRef,
) -> Sstable {
    let (data, meta) = gen_test_sstable_data(opts, kv_iter);
    let sst = Sstable { id: sst_id, meta };
    sstable_store
        .put(&sst, data, CachePolicy::Fill)
        .await
        .unwrap();
    sst
}

/// The key (with epoch 0) of an index in the test table
pub fn test_key_of(idx: usize) -> Vec<u8> {
    let user_key = format!("key_test_{:05}", idx * 2).as_bytes().to_vec();
    key_with_epoch(user_key, 233)
}

/// The value of an index in the test table
pub fn test_value_of(idx: usize) -> Vec<u8> {
    "23332333"
        .as_bytes()
        .iter()
        .cycle()
        .cloned()
        .take(idx % 100 + 1) // so that the table is not too big
        .collect_vec()
}

/// Generates a test table used in almost all table-related tests. Developers may verify the
/// correctness of their implementations by comparing the got value and the expected value
/// generated by `test_key_of` and `test_value_of`.
pub async fn gen_default_test_sstable(
    opts: SSTableBuilderOptions,
    sst_id: u64,
    sstable_store: SstableStoreRef,
) -> Sstable {
    gen_test_sstable(
        opts,
        sst_id,
        (0..TEST_KEYS_COUNT).map(|i| (test_key_of(i), HummockValue::put(test_value_of(i)))),
        sstable_store,
    )
    .await
}
