[package]
name = "risingwave_test_runner"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-machete]
ignored = ["workspace-config", "workspace-hack", "task_stats_alloc"]

[dependencies]
fail = "0.5"
sync-point = { path = "../utils/sync-point" }
workspace-hack = { path = "../workspace-hack" }
