{
 "title": "risingwave_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "actor throughtput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "irate(actor_row_count[15s])/15" }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(state_store_get_snapshot_latency_sum[5s])",
     "legendFormat": "get_snapshot_latency"
    },
    {
     "expr": "irate(state_store_iter_next_latency_sum[5s])",
     "legendFormat": "iter_next_latency"
    },
    {
     "expr": "irate(state_store_iter_next_latency_sum[5s])",
     "legendFormat": "iter_next_latency"
    },
    {
     "expr": "irate(state_store_get_latency_sum[5s])",
     "legendFormat": "get_latency"
    },
    {
     "expr": "irate(state_store_batch_write_add_l0_ssts_latency_sum[5s])",
     "legendFormat": "batch_write_add_l0_ssts_latency"
    },
    {
     "expr": "irate(state_store_batch_write_build_table_latency_sum[5s])",
     "legendFormat": "batch_write_build_table_latency"
    },
    {
     "expr": "irate(state_store_batched_write_latency_sum[5s])",
     "legendFormat": "batched_write_latency"
    }
   ]
  },
  {
   "title": "iter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "irate(state_store_iter_counts[5s])",
     "legendFormat": "iter_count"
    },
    {
     "expr": "irate(state_store_iter_next_counts[5s])",
     "legendFormat": "iter_next_count"
    },
    {
     "expr": "irate(state_store_iter_next_latency_sum[5s])",
     "legendFormat": "iter_next_latency"
    },
    {
     "expr": "irate(state_store_iter_next_latency_sum[5s])",
     "legendFormat": "iter_next_latency"
    }
   ]
  },
  {
   "title": "size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "irate(state_store_get_key_size_sum[5s])",
     "legendFormat": "get_key_size"
    },
    {
     "expr": "irate(state_store_get_value_size_sum[5s])",
     "legendFormat": "get_value_size"
    },
    {
     "expr": "irate(state_store_batched_write_size_sum[5s])",
     "legendFormat": "batched_write_size"
    }
   ]
  },
  {
   "title": "write batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "irate(state_store_batched_write_counts[5s])",
     "legendFormat": "write_batch_count"
    },
    {
     "expr": "irate(state_store_batch_write_build_table_latency_sum[5s])",
     "legendFormat": "build_table_latency"
    },
    {
     "expr": "irate(state_store_batched_write_latency_sum[5s])",
     "legendFormat": "batched_write_latency"
    },
    {
     "expr": "irate(state_store_batch_write_add_l0_ssts_latency_sum[5s])",
     "legendFormat": "add_l0_ssts_latency"
    },
    {
     "expr": "irate(state_store_batched_write_tuple_counts[5s])",
     "legendFormat": "batch_write_kvpair_count"
    },
    {
     "expr": "irate(state_store_batched_write_size_sum[5s])",
     "legendFormat": "write_batch_size"
    }
   ]
  },
  {
   "title": "count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "irate(state_store_get_counts[5s])",
     "legendFormat": "get_counts"
    },
    {
     "expr": "irate(state_store_batched_write_counts[5s])",
     "legendFormat": "write_batch_count"
    },
    {
     "expr": "irate(state_store_iter_counts[5s])",
     "legendFormat": "iter_counts"
    },
    {
     "expr": "irate(state_store_iter_next_counts[5s])",
     "legendFormat": "iter_next_counts"
    },
    {
     "expr": "irate(state_store_batched_write_tuple_counts[5s])",
     "legendFormat": "batched_write_kvpair_counts"
    }
   ]
  },
  {
   "title": "get",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "irate(state_store_get_snapshot_latency_sum[5s])",
     "legendFormat": "get_snapshot_latency"
    },
    {
     "expr": "irate(state_store_get_key_size_sum[5s])",
     "legendFormat": "get_key_size"
    },
    {
     "expr": "irate(state_store_get_counts[5s])",
     "legendFormat": "get_counts"
    },
    {
     "expr": "irate(state_store_get_value_size_sum[5s])",
     "legendFormat": "get_value_size"
    },
    {
     "expr": "irate(state_store_get_latency_sum[5s])",
     "legendFormat": "get_latency"
    }
   ]
  }
 ]
}