#!/bin/bash

set -euo pipefail

echo "/* This file was auto-generated by grafanalib. DO NOT EDIT */" > risingwave-dashboard.json
generate-dashboard risingwave-dashboard.py >> risingwave-dashboard.json
