#!/usr/bin/env zsh

# If core dump is enabled by RiseDev and we're on an Apple Silicon platform,
# codesign the binary before running.
# https://developer.apple.com/forums/thread/694233?answerId=695943022#695943022
if [[ "$ENABLE_COREDUMP" == "true" ]]; then
    codesign -s - -f --entitlements scripts/coredump/coredump.entitlements "$1"
fi

exec "$@"
