#!/bin/bash
set -ex

docker compose exec kafka kafka-topics --create --topic taxi --partitions 1 --replication-factor 1 --bootstrap-server=127.0.0.1:29092
sleep 5

psql -U root -h 127.0.0.1 -p 4566 -d dev -a -f taxi-start.sql || {
  echo "failed to initialize db for taxi"
  exit 1
}
sleep 2

pip3 install -r server/model/requirements.txt