---
version: "3"
services:
  risingwave-standalone:
    <<: *image
    command: "standalone --meta-opts=\" \
                    --listen-addr 0.0.0.0:5690 \
                    --advertise-addr 0.0.0.0:5690 \
                    --dashboard-host 0.0.0.0:5691 \
                    --prometheus-host 0.0.0.0:1250 \
                    --connector-rpc-endpoint 0.0.0.0:50051 \
                    --backend etcd \
                    --etcd-endpoints etcd-0:2388 \
                    --state-store hummock+azblob://<bucket-name> \
                    --data-directory hummock_001 \
                    --config-path /risingwave.toml\" \
                 --compute-opts=\" \
                    --config-path /risingwave.toml \
                    --listen-addr 0.0.0.0:5688 \
                    --prometheus-listener-addr 0.0.0.0:1222 \
                    --advertise-addr 0.0.0.0:5688 \
                    --async-stack-trace verbose \
                    --connector-rpc-endpoint 0.0.0.0:50051 \
                    #--parallelism 4 \
                    #--total-memory-bytes 8589934592 \
                    --role both \
                    --meta-address http://0.0.0.0:5690\" \
                 --frontend-opts=\" \
                   --config-path /risingwave.toml \
                   --listen-addr 0.0.0.0:4566 \
                   --advertise-addr 0.0.0.0:4566 \
                   --prometheus-listener-addr 0.0.0.0:2222 \
                   --health-check-listener-addr 0.0.0.0:6786 \
                   --meta-addr http://0.0.0.0:5690\" \
                 --compactor-opts=\" \
                   --listen-addr 0.0.0.0:6660 \
                   --prometheus-listener-addr 0.0.0.0:1260 \
                   --advertise-addr 0.0.0.0:6660 \
                   --meta-address http://0.0.0.0:5690\""
    expose:
      - "6660"
      - "1260"
      - "4566"
      - "5688"
      - "1222"
      - "5690"
      - "1250"
      - "5691"
    depends_on:
      - "etcd-0"
    env_file: multiple_object_storage.env
  etcd-0:
    extends:
      file: docker-compose.yml
      service: etcd-0
  grafana-0:
    extends:
      file: docker-compose.yml
      service: grafana-0
  meta-node-0:
    extends:
      file: docker-compose.yml
      service: meta-node-0
    command:
      - meta-node
      - "--listen-addr"
      - "0.0.0.0:5690"
      - "--advertise-addr"
      - "meta-node-0:5690"
      - "--dashboard-host"
      - "0.0.0.0:5691"
      - "--prometheus-host"
      - "0.0.0.0:1250"
      - "--backend"
      - etcd
      - "--etcd-endpoints"
      - "etcd-0:2388"
      - "--state-store"
      - "hummock+azblob://<container_name>"
      - "--data-directory"
      - "hummock_001"
      - "--config-path"
      - /risingwave.toml
    depends_on:
      - etcd-0
    env_file: multiple_object_storage.env
  prometheus-0:
    extends:
      file: docker-compose.yml
      service: prometheus-
  message_queue:
    extends:
      file: docker-compose.yml
      service: message_queue
volumes:
  etcd-0:
    external: false
  grafana-0:
    external: false
  prometheus-0:
    external: false
  message_queue:
    external: false
