[tasks.do-apply-planner-test]
description = "Apply planner test data"
category = "RiseDev - Test"
dependencies = ["install-nextest"]
script = '''
#!/usr/bin/env bash
set -e

UPDATE_EXPECT=1 cargo nextest run -p risingwave_planner_test --retries 0

echo "$(tput setaf 2)Diff applied!$(tput sgr 0)"
echo "Tip: use the alias $(tput setaf 4)./risedev dapt$(tput sgr0)."
'''

[tasks.dapt]
alias = "do-apply-planner-test"

[tasks.run-planner-test]
description = "Run planner test"
category = "RiseDev - Test"
dependencies = ["install-nextest"]
script = '''
#!/usr/bin/env bash
set -e

cargo nextest run -p risingwave_planner_test --retries 0 "$@"
'''
