[package]
name = "risingwave_java_binding"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
bytes = "1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
itertools = "0.11"
jni = "0.21.1"
prost = "0.11"
risingwave_common = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_object_store = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_storage = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "fs",
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tracing = "0.1"

[dev-dependencies]
risingwave_expr = { workspace = true }

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "data-chunk-payload-generator"
test = false
bench = false

[[bin]]
name = "data-chunk-payload-convert-generator"
test = false
bench = false
