[package]
name = "risingwave_java_binding"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
risingwave_jni_core = { workspace = true }

[dev-dependencies]
risingwave_expr = { workspace = true }

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "data-chunk-payload-generator"
test = false
bench = false

[[bin]]
name = "data-chunk-payload-convert-generator"
test = false
bench = false
