[package]
name = "workspace-static-link"
version = "0.1.11"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
enabled = ["isahc", "openssl", "rdkafka_vendored"]
# Use a feature flag to control enable or not, otherwise `cargo test` will compile all dependencies.

[dependencies]
isahc = { version = "1", optional = true, default-features = false, features = ["static-ssl", "static-curl"] }
openssl = { version = "0.10", optional = true, features = ["vendored"] }
rdkafka_vendored = { package = "madsim-rdkafka", version = "=0.2.8-alpha", optional = true, features = ["ssl-vendored", "gssapi-vendored"] }
# workspace-hack = { version = "0.1", path = "../../workspace-hack" }
# Don't add workspace-hack into this crate!
