[batch.developer]
batch_chunk_size = 1024
batch_output_channel_size = 64

[meta]
dangerous_max_idle_secs = 1800
disable_recovery = true
max_heartbeat_interval_secs = 600

[server]
connection_pool_size = 16
heartbeat_interval_ms = 1000
max_heartbeat_interval_secs = 600

[storage]
block_cache_capacity_mb = 4096
block_size_kb = 1024
bloom_false_positive = 0.01
compactor_memory_limit_mb = 5120
data_directory = "hummock_001"
meta_cache_capacity_mb = 1024
shared_buffer_capacity_mb = 4096
sstable_size_mb = 256

[storage.file_cache]
cache_file_fallocate_unit_mb = 512
cache_file_max_write_size_mb = 4
cache_meta_fallocate_unit_mb = 16
capacity_mb = 1024
total_buffer_capacity_mb = 128

[streaming]
barrier_interval_ms = 1000
checkpoint_frequency = 10
in_flight_barrier_nums = 10

[streaming.developer]
stream_chunk_size = 1024
stream_connector_message_buffer_size = 16
stream_enable_executor_row_count = false
stream_enable_managed_cache = true
unsafe_stream_extreme_cache_size = 1024
unsafe_stream_hash_agg_cache_size = 65536
unsafe_stream_join_cache_size = 65536
