[server]
heartbeat_interval_ms = 1000
max_heartbeat_interval_secs = 600
connection_pool_size = 16

[meta]

[batch]

[storage]
shared_buffer_capacity_mb = 1024
sstable_size_mb = 256
block_size_kb = 64
bloom_false_positive = 0.001
data_directory = "hummock_001"
block_cache_capacity_mb = 2048
meta_cache_capacity_mb = 256
compactor_memory_limit_mb = 1024

