[streaming.developer]
stream_enable_executor_row_count = false
stream_connector_message_buffer_size = 16
stream_unsafe_extreme_cache_size = 10
stream_chunk_size = 5

[system]
barrier_interval_ms = 2000
checkpoint_frequency = 1
sstable_size_mb = 256
parallel_compact_size_mb = 512
block_size_kb = 64
bloom_false_positive = 0.001
backup_storage_url = "memory"
backup_storage_directory = "backup"
max_concurrent_creating_streaming_jobs = 1
pause_on_next_bootstrap = false
