[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment", "-Ctarget-feature=+avx2", "--cfg", "tokio_unstable"
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment", "-Ctarget-feature=+v7,+neon", "--cfg", "tokio_unstable"
]

[build]
rustflags = ["-Ctarget-cpu=native", "--cfg", "tokio_unstable"]
