[package]
name = "risingwave_frontend_test_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.8"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
risingwave_frontend = { path = ".." }
risingwave_sqlparser = { path = "../../sqlparser" }
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
walkdir = "2"

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "planner-test-apply"
path = "src/bin/apply.rs"
