CREATE TABLE compatible_data (
  id integer PRIMARY KEY,
  c_boolean boolean,
  c_smallint smallint,
  c_integer integer,
  c_bigint bigint,
  c_decimal decimal,
  c_real real,
  c_double_precision double precision,
  c_varchar varchar,
  c_bytea bytea,
  c_date date,
  c_time time,
  c_timestamp timestamp,
  c_timestamptz timestamptz,
  c_interval interval,
  c_jsonb jsonb,
  c_boolean_array boolean[],
  c_smallint_array smallint[],
  c_integer_array integer[],
  c_bigint_array bigint[],
  c_decimal_array decimal[],
  c_real_array real[],
  c_double_precision_array double precision[],
  c_varchar_array varchar[],
  c_bytea_array bytea[],
  c_date_array date[],
  c_time_array time[],
  c_timestamp_array timestamp[],
  c_timestamptz_array timestamptz[],
  c_interval_array interval[],
  c_jsonb_array jsonb[],
  c_struct STRUCT<s_int32 INTEGER, s_bool boolean>,
) WITH (
    connector = 'kafka',
    topic = 'compatible_data',
    properties.bootstrap.server = 'message_queue:29092',
    scan.startup.mode = 'earliest'
) FORMAT PLAIN ENCODE JSON;
