[workspace]
members = [
  "batch",
  "bench",
  "common",
  "compute",
  "connector",
  "frontend",
  "meta",
  "prost",
  "prost/helpers",
  "risedev",
  "rpc_client",
  "source",
  "sqlparser",
  "storage",
  "stream",
  "tests/regress",
  "utils/logging",
  "utils/memcomparable",
  "utils/pgwire",
]
