[package]
name = "risingwave_mem_table_test"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
async-trait = "0.1"
bytes = { version = "1" }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = "0.2.9"
risingwave_common = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_stream = { workspace = true }
risingwave_storage = { workspace = true, features = ["test"] }
risingwave_hummock_test = { workspace = true, features = ["test"] }
tokio = { version = "0.2", package = "madsim-tokio" }

[dev-dependencies]
risingwave_hummock_sdk = { workspace = true, features = [] }

[lints]
workspace = true
