jobs:
  misc-check:
    runs-on: ubuntu-latest
    name: misc-check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install required tools
        run: |
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${BINARY}.tar.gz -O - | tar xz && sudo mv ${BINARY} /usr/bin/yq
          sudo apt install -y protobuf-compiler -o Acquire::Retries=3
          curl -sSL \
            https://github.com/uber/prototool/releases/download/v1.8.0/prototool-$(uname -s)-$(uname -m).tar.gz | \
            sudo tar -C /usr/local --strip-components 1 -xz
          curl -sSL \
            "https://github.com/bufbuild/buf/releases/download/v${BUF_VERSION}/buf-$(uname -s)-$(uname -m).tar.gz" | \
            sudo tar -xvzf - -C /usr/local --strip-components 1
        env:
          YQ_VERSION: v4.16.1
          BINARY: yq_linux_amd64
          BUF_VERSION: 1.0.0-rc6

      - name: Check CI workflows are up-to-date
        run: |
          ./.github/workflow-template/generate.sh --check

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: legacy # we assume legacy folder has no script. gradle wrapper also won't pass shellcheck.

      - name: Check protobuf code format
        run: |
          prototool format -d
        working-directory: proto

      - name: Lint protobuf
        run: |
          buf lint
        working-directory: proto
