jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs:
      - compute-node-build-release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: ".github/changelog.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v2
        name: Download risingwave binary
        with:
          name: risingwave-release
          path: .

      - name: package as tar
        run: |
          chmod +x risingwave
          tar -czvf risingwave-${GITHUB_REF_NAME}-x86_64-unknown-linux.tar.gz risingwave
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: add artifact
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: risingwave-${{ github.ref_name }}-x86_64-unknown-linux.tar.gz
          asset_name: risingwave-${{ github.ref_name }}-x86_64-unknown-linux.tar.gz
          asset_content_type: application/tar+gzip
