[env]
OS = { source = "${CARGO_MAKE_RUST_TARGET_OS}", mapping = { linux = "linux", macos = "darwin" } }
ARCH = { source = "${CARGO_MAKE_RUST_TARGET_ARCH}", mapping = { x86_64 = "amd64", aarch64 = "arm64" } }
SYSTEM = "${OS}-${ARCH}"
SYSTEM_AMD64 = "${OS}-amd64" # some components do not support darwin-arm64 for now, use amd64 for fallback
PREFIX = "${PWD}/.risingwave"
PREFIX_BIN = "${PREFIX}/bin"
PREFIX_CONFIG = "${PREFIX}/config"
PREFIX_DATA = "${PREFIX}/data"
PREFIX_LOG = "${PREFIX}/log"
PREFIX_TMP = "${PREFIX}/tmp"
PREFIX_UI = "${PREFIX}/ui"

HUMMOCK_PATH = "${PREFIX_DATA}/hummock"
BUILD_MODE_DIR = { source = "${ENABLE_RELEASE_PROFILE}", default_value = "debug", mapping = { true = "release" } }
RISINGWAVE_BUILD_PROFILE = { source = "${ENABLE_RELEASE_PROFILE}", default_value = "dev", mapping = { true = "release" } }

[tasks.prepare-dir]
private = true
script = '''
#!@duckscript
echo "Using ${PREFIX} as base folder"
mkdir "${PREFIX}"
mkdir "${PREFIX_BIN}"
mkdir "${PREFIX_TMP}"
mkdir "${PREFIX_DATA}"
mkdir "${PREFIX_CONFIG}"
mkdir "${PREFIX_CONFIG}/mcli"
mkdir "${PREFIX_LOG}"
mkdir "${HUMMOCK_PATH}"
'''

[tasks.check-risedev-configured]
private = true
condition = { env_not_set = [ "RISEDEV_CONFIGURED" ] }
script = '''
#!@shell
set -e
echo "RiseDev is not configured, please run ./risedev configure"
exit 1
'''

[tasks.prepare]
category = "Misc"
description = "Create .risingwave folder for storing temporary files and data"
dependencies = ["prepare-dir", "check-risedev-configured"]
