[tasks.configure-if-not-configured]
condition = { env_not_set = [ "RISEDEV_CONFIGURED" ] }
script = '''
#!/bin/bash
set -e
ENV_PATH="$(pwd)/risedev-components.user.env"
cd rust && cargo run --bin risedev-config -- "${ENV_PATH}" --default
'''

[tasks.configure]
script = '''
#!/bin/bash
set -e
ENV_PATH="$(pwd)/risedev-components.user.env"
cd rust && cargo run --bin risedev-config -- "${ENV_PATH}"
'''
