extend = "common.toml"

[env]
# Nginx config


[tasks.download-nginx]
category = "RiseDev - Components"
dependencies = ["prepare"]
description = "Download and extract Nginx"
script = '''
#!/bin/bash
set -e
if [ -f "${PREFIX_BIN}/nginx" ]; then
    exit 0
fi
echo "Nginx not found, downloading"
# TODO: Download bin depending on system
brew install nginx
cp /opt/homebrew/bin/nginx "${PREFIX_BIN}/nginx"
chmod +x "${PREFIX_BIN}/nginx"
brew uninstall nginx

"${PREFIX_BIN}/nginx" -v
exit 0
'''
