extend = "common.toml"

[env]
# Nginx config


[tasks.download-nginx]
category = "RiseDev - Components"
dependencies = ["prepare"]
description = "Download and extract Nginx. Used as Load Balancer"
script = '''
#!/bin/bash
set -e

# TODO: remove exit here
exit 0

if [ -f "${PREFIX_BIN}/nginx" ]; then
    exit 0
fi
echo "Load balancer Nginx not found, downloading"

# Handle everything not mac here
if ! command -v brew &> /dev/null
then
    echo "brew could not be found. Installing Nginx from source"
    if ! command -v make &> /dev/null ; then echo "make not installed. Please install make or use homebrew to install Nginx"; exit 1; fi 
    if ! command -v wget &> /dev/null ; then echo "wget not installed. Please install wget or use homebrew to install Nginx"; exit 1; fi 
    if ! command -v tar  &> /dev/null ; then echo "tar not installed.  Please install tar  or use homebrew to install Nginx"; exit 1; fi 


    tmpdir=$(mktemp -d)
    bin_dir=$(pwd)/.risingwave/bin

    # Download nginx source
    pushd $tmpdir
    wget http://nginx.org/download/nginx-1.23.3.tar.gz  
    tar -zxvf nginx-1.23.3.tar.gz  

    # configure and install
    cd nginx-1.23.3
    ./configure --without-http_rewrite_module --with-http_v2_module --prefix=${bin_dir} --sbin-path=${bin_dir}

    make
    make install

    # get bin and cleanup
    popd 
    rm -rf ${tmpdir}
    exit 0
fi

# Handle installation on mac here
brew install nginx
cp /opt/homebrew/bin/nginx "${PREFIX_BIN}/nginx"
chmod +x "${PREFIX_BIN}/nginx"
brew uninstall nginx

"${PREFIX_BIN}/nginx" -v
exit 0
'''




