[package]
name = "workspace-config"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Use a feature flag to control enable or not, otherwise `cargo test` will compile all dependencies.
rw-static-link = ["openssl", "rdkafka"]
rw-dynamic-link = ["zstd-sys"]

[dependencies]
log = { version = "0.4", features = ["release_max_level_debug"] }
openssl = { version = "0.10", optional = true, features = ["vendored"] }
rdkafka = { workspace = true, optional = true, features = ["cmake-build", "ssl-vendored", "gssapi-vendored"] }
tracing = { version = "0.1", features = ["release_max_level_debug"] }
zstd-sys = { version = "2", optional = true, default-features = false, features = ["pkg-config"] }
# workspace-hack = { path = "../../workspace-hack" }
# Don't add workspace-hack into this crate!
