init_sqls = [
    'CREATE SCHEMA IF NOT EXISTS demo_db',
    'DROP TABLE IF EXISTS demo_db.sink_auto_schema_change_drop_column PURGE',
    '''
    CREATE TABLE demo_db.sink_auto_schema_change_drop_column (
        id long,
        v1 int,
        v2 string,
        v3 long
    ) USING iceberg TBLPROPERTIES ('format-version'='2');
    '''
]

slt = 'test_case/iceberg_sink_auto_schema_change_drop_column.slt'

verify_schema = ['long', 'int', 'long']

verify_sql = 'SELECT id, v1, v3 FROM demo_db.sink_auto_schema_change_drop_column ORDER BY id ASC'

verify_data = """
1,10,100
2,20,200
3,30,300
"""

drop_sqls = [
    'DROP TABLE IF EXISTS demo_db.sink_auto_schema_change_drop_column PURGE',
    'DROP SCHEMA IF EXISTS demo_db'
]
