init_sqls = [
    'CREATE SCHEMA IF NOT EXISTS demo_db',
    'DROP TABLE IF EXISTS demo_db.field_id_gap_upsert_table PURGE',
    '''
    CREATE TABLE demo_db.field_id_gap_upsert_table (
    pad int,
    k int,
    b int
    ) USING iceberg
    TBLPROPERTIES ('format-version'='2');
    ''',
    'ALTER TABLE demo_db.field_id_gap_upsert_table DROP COLUMN pad'
]

slt = 'test_case/iceberg_sink_field_id_gap_upsert_table.slt'

verify_schema = ['int','int']

verify_sql = 'SELECT * FROM demo_db.field_id_gap_upsert_table ORDER BY k ASC'

verify_data = """
1,600
"""

drop_sqls = [
 'DROP TABLE IF EXISTS demo_db.field_id_gap_upsert_table PURGE',
 'DROP SCHEMA IF EXISTS demo_db'
]
