# Override `template.yml` with contents in this file. Please run `generate.sh` to update the corresponding files.

name: CI (main-cronjob)

on:
  # Triggers the workflow everyday 00:00
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
