# Override `template.yml` with contents in this file. Please run `generate.sh` to update the corresponding files.

name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - "forks/*"

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read # This is required for actions/checkout
