// Copyright 2023 RisingWave Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::collections::hash_map::HashMap;
use std::collections::{BTreeMap, HashSet};
use std::num::NonZeroUsize;
use std::ops::Deref;
use std::sync::{Arc, LazyLock};

use anyhow::Context;
use assert_matches::assert_matches;
use enum_as_inner::EnumAsInner;
use itertools::Itertools;
use risingwave_common::bail;
use risingwave_common::buffer::Bitmap;
use risingwave_common::catalog::{generate_internal_table_name_with_type, TableId};
use risingwave_common::hash::{ActorId, ActorMapping, ParallelUnitId, ParallelUnitMapping};
use risingwave_pb::catalog::Table;
use risingwave_pb::meta::table_fragments::fragment::FragmentDistributionType;
use risingwave_pb::meta::table_fragments::Fragment;
use risingwave_pb::stream_plan::stream_fragment_graph::{
    StreamFragment, StreamFragmentEdge as StreamFragmentEdgeProto,
};
use risingwave_pb::stream_plan::stream_node::NodeBody;
use risingwave_pb::stream_plan::{
    agg_call_state, DispatchStrategy, Dispatcher, DispatcherType, MergeNode, StreamActor,
    StreamFragmentGraph as StreamFragmentGraphProto, StreamNode,
};

use self::schedule::Distribution;
use super::{CreateStreamingJobContext, ScheduledLocations};
use crate::manager::{
    IdCategory, IdCategoryType, IdGeneratorManager, IdGeneratorManagerRef, StreamingClusterInfo,
    StreamingJob,
};
use crate::model::{DispatcherId, FragmentId};
use crate::storage::MetaStore;
use crate::MetaResult;

mod schedule;

/// A wrapper to distinguish global ID generated by the [`IdGeneratorManager`] and the local ID from
/// the frontend.
#[derive(Clone, Copy, Debug, Hash, Eq, PartialEq, PartialOrd, Ord)]
struct GlobalId<const TYPE: IdCategoryType>(u32);

impl<const TYPE: IdCategoryType> GlobalId<TYPE> {
    pub const fn new(id: u32) -> Self {
        Self(id)
    }

    pub fn as_global_id(&self) -> u32 {
        self.0
    }
}

/// Utility for converting local IDs into pre-allocated global IDs by adding an `offset`.
///
/// This requires the local IDs exactly a permutation of the range `[0, len)`.
#[derive(Clone, Copy, Debug)]
struct GlobalIdGen<const TYPE: IdCategoryType> {
    offset: u32,
    len: u32,
}

impl<const TYPE: IdCategoryType> GlobalIdGen<TYPE> {
    /// Pre-allocate a range of IDs with the given `len` and return the generator.
    pub async fn new<S: MetaStore>(id_gen: &IdGeneratorManager<S>, len: u64) -> MetaResult<Self> {
        let offset = id_gen.generate_interval::<TYPE>(len).await?;
        Ok(Self {
            offset: offset as u32,
            len: len as u32,
        })
    }

    /// Convert local id to global id. Panics if `id >= len`.
    pub fn to_global_id(self, local_id: u32) -> GlobalId<TYPE> {
        assert!(
            local_id < self.len,
            "id {} is out of range (len: {})",
            local_id,
            self.len
        );
        GlobalId(local_id + self.offset)
    }
}

type GlobalFragmentId = GlobalId<{ IdCategory::Fragment }>;
type GlobalFragmentIdGen = GlobalIdGen<{ IdCategory::Fragment }>;

type GlobalTableIdGen = GlobalIdGen<{ IdCategory::Table }>;

type GlobalActorId = GlobalId<{ IdCategory::Actor }>;
type GlobalActorIdGen = GlobalIdGen<{ IdCategory::Actor }>;

/// A list of actors with order.
#[derive(Debug, Clone)]
struct OrderedActorLink(pub Vec<GlobalActorId>);

impl OrderedActorLink {
    pub fn as_global_ids(&self) -> Vec<u32> {
        self.0.iter().map(|x| x.as_global_id()).collect()
    }
}

#[derive(Debug)]
struct StreamActorUpstream {
    /// Upstream actors
    actors: OrderedActorLink,
    /// associate fragment id
    fragment_id: GlobalFragmentId,
}

/// [`StreamActorBuilder`] builds a stream actor in a stream DAG.
#[derive(Debug)]
struct StreamActorBuilder {
    /// actor id field
    actor_id: GlobalActorId,

    /// associated fragment id
    fragment_id: GlobalFragmentId,

    /// associated stream node
    nodes: Arc<StreamNode>,

    downstreams: HashMap<DispatcherId, Dispatcher>,

    /// upstreams, exchange node operator_id -> upstream actor ids
    upstreams: HashMap<EdgeId, StreamActorUpstream>,

    vnode_bitmap: Option<Bitmap>,
}

impl StreamActorBuilder {
    pub fn new(
        actor_id: GlobalActorId,
        fragment_id: GlobalFragmentId,
        vnode_bitmap: Option<Bitmap>,
        node: Arc<StreamNode>,
    ) -> Self {
        Self {
            actor_id,
            fragment_id,
            nodes: node,
            downstreams: HashMap::new(),
            upstreams: HashMap::new(),
            vnode_bitmap,
        }
    }

    pub fn fragment_id(&self) -> GlobalFragmentId {
        self.fragment_id
    }

    pub fn add_dispatcher(&mut self, dispatcher: Dispatcher) {
        self.downstreams
            .try_insert(dispatcher.dispatcher_id, dispatcher)
            .unwrap();
    }

    fn rewrite(&self) -> MetaResult<StreamNode> {
        self.rewrite_inner(&self.nodes, 0)
    }

    /// Build stream actor inside, two works will be done:
    /// 1. replace node's input with [`MergeNode`] if it is `ExchangeNode`, and swallow
    /// mergeNode's input.
    /// 2. ignore root node when it's `ExchangeNode`.
    /// 3. replace node's `ExchangeNode` input with [`MergeNode`] and resolve its upstream actor
    /// ids if it is a `ChainNode`.
    fn rewrite_inner(&self, stream_node: &StreamNode, depth: usize) -> MetaResult<StreamNode> {
        match stream_node.get_node_body()? {
            NodeBody::Exchange(exchange) => {
                if depth == 0 {
                    bail!(
                        "there should be no ExchangeNode on the top of the plan node: {:#?}",
                        stream_node
                    )
                }
                assert!(!stream_node.get_fields().is_empty());
                assert!(stream_node.input.is_empty());

                let upstreams = &self.upstreams[&EdgeId::Internal {
                    exchange_id: stream_node.get_operator_id(),
                }];

                Ok(StreamNode {
                    node_body: Some(NodeBody::Merge(MergeNode {
                        upstream_actor_id: upstreams.actors.as_global_ids(),
                        upstream_fragment_id: upstreams.fragment_id.as_global_id(),
                        upstream_dispatcher_type: exchange.get_strategy()?.r#type,
                        fields: stream_node.get_fields().clone(),
                    })),
                    identity: "MergeExecutor".to_string(),
                    ..stream_node.clone()
                })
            }

            NodeBody::Chain(chain_node) => {
                let input = stream_node.get_input();
                assert_eq!(input.len(), 2);

                let merge_node = &input[0];
                assert_matches!(merge_node.node_body, Some(NodeBody::Merge(_)));
                let batch_plan_node = &input[1];
                assert_matches!(batch_plan_node.node_body, Some(NodeBody::BatchPlan(_)));

                let upstreams = &self.upstreams[&EdgeId::UpstreamExternal {
                    upstream_table_id: chain_node.table_id,
                    downstream_fragment_id: self.fragment_id,
                }];

                let upstream_actor_id = upstreams.actors.as_global_ids();
                assert_eq!(upstream_actor_id.len(), 1);

                let chain_input = vec![
                    StreamNode {
                        input: vec![],
                        stream_key: merge_node.stream_key.clone(),
                        node_body: Some(NodeBody::Merge(MergeNode {
                            upstream_actor_id,
                            upstream_fragment_id: upstreams.fragment_id.as_global_id(),
                            upstream_dispatcher_type: DispatcherType::NoShuffle as _,
                            fields: chain_node.upstream_fields.clone(),
                        })),
                        fields: chain_node.upstream_fields.clone(),
                        operator_id: merge_node.operator_id,
                        identity: "MergeExecutor".to_string(),
                        append_only: stream_node.append_only,
                    },
                    batch_plan_node.clone(),
                ];

                Ok(StreamNode {
                    input: chain_input,
                    stream_key: stream_node.stream_key.clone(),
                    node_body: Some(NodeBody::Chain(chain_node.clone())),
                    operator_id: stream_node.operator_id,
                    identity: "ChainExecutor".to_string(),
                    fields: chain_node.upstream_fields.clone(),
                    append_only: stream_node.append_only,
                })
            }

            _ => {
                let mut new_stream_node = stream_node.clone();
                for (input, new_input) in
                    stream_node.input.iter().zip_eq(&mut new_stream_node.input)
                {
                    *new_input = self.rewrite_inner(input, depth + 1)?;
                }
                Ok(new_stream_node)
            }
        }
    }

    /// Build an actor after seal.
    pub fn build(self, ctx: &CreateStreamingJobContext) -> MetaResult<StreamActor> {
        let rewritten_nodes = self.rewrite()?;

        // TODO: store each upstream separately
        let upstream_actor_id = self
            .upstreams
            .into_values()
            .flat_map(|StreamActorUpstream { actors, .. }| actors.0)
            .map(|x| x.as_global_id())
            .collect();

        Ok(StreamActor {
            actor_id: self.actor_id.as_global_id(),
            fragment_id: self.fragment_id.as_global_id(),
            nodes: Some(rewritten_nodes),
            dispatcher: self.downstreams.into_values().collect(),
            upstream_actor_id,
            colocated_upstream_actor_id: None, // TODO: remove this
            vnode_bitmap: self.vnode_bitmap.map(|b| b.to_protobuf()),
            mview_definition: ctx.streaming_definition.clone(),
        })
    }
}

struct Node<'a> {
    fragment_id: GlobalFragmentId,
    actor_ids: &'a [GlobalActorId],
    distribution: &'a Distribution,
}

type StreamActorGraph = HashMap<GlobalFragmentId, Vec<StreamActor>>;
type ActorLocations = BTreeMap<GlobalActorId, ParallelUnitId>;

pub type StreamGraph = BTreeMap<FragmentId, Fragment>;

#[derive(Default)]
struct ExternalChange {
    new_downstreams: HashMap<DispatcherId, Dispatcher>,
}

impl ExternalChange {
    pub fn add_dispatcher(&mut self, dispatcher: Dispatcher) {
        self.new_downstreams
            .try_insert(dispatcher.dispatcher_id, dispatcher)
            .unwrap();
    }
}

/// [`StreamGraphBuilder`] build a stream graph. It injects some information to achieve
/// dependencies. See `build_inner` for more details.
#[derive(Default)]
struct StreamGraphBuilder {
    actor_builders: BTreeMap<GlobalActorId, StreamActorBuilder>,

    locations: BTreeMap<GlobalActorId, ParallelUnitId>,

    external_changes: BTreeMap<GlobalActorId, ExternalChange>,
}

impl StreamGraphBuilder {
    /// Insert new generated actor.
    pub fn add_actor(
        &mut self,
        actor_id: GlobalActorId,
        fragment_id: GlobalFragmentId,
        parallel_unit_id: ParallelUnitId,
        vnode_bitmap: Option<Bitmap>,
        node: Arc<StreamNode>,
    ) {
        self.actor_builders
            .try_insert(
                actor_id,
                StreamActorBuilder::new(actor_id, fragment_id, vnode_bitmap, node),
            )
            .unwrap();

        self.record_location(actor_id, parallel_unit_id);
    }

    fn record_location(&mut self, actor_id: GlobalActorId, parallel_unit_id: ParallelUnitId) {
        self.locations
            .try_insert(actor_id, parallel_unit_id)
            .unwrap();
    }

    fn new_hash_dispatcher(
        column_indices: &[u32],
        downstream_fragment_id: GlobalFragmentId,
        downstream_actors: &[GlobalActorId],
        downstream_actor_mapping: ActorMapping,
    ) -> Dispatcher {
        Dispatcher {
            r#type: DispatcherType::Hash as _,
            column_indices: column_indices.to_vec(),
            hash_mapping: Some(downstream_actor_mapping.to_protobuf()),
            dispatcher_id: downstream_fragment_id.as_global_id() as u64,
            downstream_actor_id: OrderedActorLink(downstream_actors.to_vec()).as_global_ids(), /* TODO */
        }
    }

    fn new_normal_dispatcher(
        dispatcher_type: DispatcherType,
        downstream_fragment_id: GlobalFragmentId,
        downstream_actors: &[GlobalActorId],
    ) -> Dispatcher {
        assert_ne!(dispatcher_type, DispatcherType::Hash);
        Dispatcher {
            r#type: dispatcher_type as _,
            column_indices: Vec::new(),
            hash_mapping: None,
            dispatcher_id: downstream_fragment_id.as_global_id() as u64,
            downstream_actor_id: OrderedActorLink(downstream_actors.to_vec()).as_global_ids(), /* TODO */
        }
    }

    pub fn add_dispatcher(&mut self, actor_id: GlobalActorId, dispatcher: Dispatcher) {
        if let Some(actor_builder) = self.actor_builders.get_mut(&actor_id) {
            actor_builder.add_dispatcher(dispatcher);
        } else {
            self.external_changes
                .entry(actor_id)
                .or_default()
                .add_dispatcher(dispatcher);
        }
    }

    /// Add dependency between two connected node in the graph.
    pub fn add_link<'a>(
        &mut self,
        upstream: Node<'a>,
        downstream: Node<'a>,
        edge: &'a StreamFragmentEdge,
    ) {
        let dt = edge.dispatch_strategy.r#type();

        match dt {
            DispatcherType::NoShuffle => {
                for (upstream_id, downstream_id) in upstream
                    .actor_ids
                    .iter()
                    .zip_eq(downstream.actor_ids.iter())
                {
                    let upstream_location = self.locations[upstream_id];
                    let downstream_location = self.locations[downstream_id];
                    assert_eq!(upstream_location, downstream_location);

                    self.add_dispatcher(
                        *upstream_id,
                        Self::new_normal_dispatcher(dt, downstream.fragment_id, &[*downstream_id]),
                    );

                    // TODO: refactor
                    self.actor_builders
                        .get_mut(downstream_id)
                        .unwrap()
                        .upstreams
                        .try_insert(
                            edge.id,
                            StreamActorUpstream {
                                actors: OrderedActorLink(vec![*upstream_id]),
                                fragment_id: upstream.fragment_id,
                            },
                        )
                        .unwrap_or_else(|_| {
                            panic!(
                                "duplicated exchange input {:?} for no-shuffle actors {:?} -> {:?}",
                                edge.id, upstream_id, downstream_id
                            )
                        });
                }
            }

            // Otherwise, make m * n links between actors.
            DispatcherType::Hash | DispatcherType::Broadcast | DispatcherType::Simple => {
                let dispatcher = if let DispatcherType::Hash = dt {
                    let downstream_locations: HashMap<ParallelUnitId, ActorId> = downstream
                        .actor_ids
                        .iter()
                        .map(|&actor_id| (self.locations[&actor_id], actor_id.as_global_id()))
                        .collect();
                    let actor_mapping = downstream
                        .distribution
                        .as_hash()
                        .unwrap()
                        .to_actor(&downstream_locations);

                    Self::new_hash_dispatcher(
                        &edge.dispatch_strategy.column_indices,
                        downstream.fragment_id,
                        downstream.actor_ids,
                        actor_mapping.clone(),
                    )
                } else {
                    Self::new_normal_dispatcher(dt, downstream.fragment_id, downstream.actor_ids)
                };

                for upstream_id in upstream.actor_ids {
                    self.add_dispatcher(*upstream_id, dispatcher.clone());
                }

                for downstream_id in downstream.actor_ids {
                    self.actor_builders
                        .get_mut(downstream_id)
                        .unwrap()
                        .upstreams
                        .try_insert(
                            edge.id,
                            StreamActorUpstream {
                                actors: OrderedActorLink(upstream.actor_ids.to_vec()),
                                fragment_id: upstream.fragment_id,
                            },
                        )
                        .unwrap_or_else(|_| {
                            panic!(
                                "duplicated exchange input {:?} for actors {:?} -> {:?}",
                                edge.id, upstream.actor_ids, downstream.actor_ids
                            )
                        });
                }
            }

            DispatcherType::Unspecified => unreachable!(),
        }
    }

    /// Build final stream DAG with dependencies with current actor builders.
    #[allow(clippy::type_complexity)]
    pub fn build(
        self,
        ctx: &CreateStreamingJobContext,
    ) -> MetaResult<(StreamActorGraph, ActorLocations)> {
        let mut graph: StreamActorGraph = HashMap::new();

        for builder in self.actor_builders.into_values() {
            let fragment_id = builder.fragment_id();
            let actor = builder.build(ctx)?;
            graph.entry(fragment_id).or_default().push(actor);
        }

        Ok((graph, self.locations))
    }
}

/// The mutable state when building actor graph.
struct BuildActorGraphState {
    /// The stream graph builder, to build streaming DAG.
    stream_graph_builder: StreamGraphBuilder,

    /// When converting fragment graph to actor graph, we need to know which actors belong to a
    /// fragment.
    fragment_actors: HashMap<GlobalFragmentId, Vec<GlobalActorId>>,

    /// The next local actor id to use.
    next_local_id: u32,

    /// The global actor id generator.
    actor_id_gen: GlobalActorIdGen,
}

impl BuildActorGraphState {
    /// Create an empty state with the given id generator.
    fn new(actor_id_gen: GlobalActorIdGen) -> Self {
        Self {
            stream_graph_builder: Default::default(),
            fragment_actors: Default::default(),
            next_local_id: 0,
            actor_id_gen,
        }
    }

    /// Get the next global actor id.
    fn next_actor_id(&mut self) -> GlobalActorId {
        let local_id = self.next_local_id;
        self.next_local_id += 1;

        self.actor_id_gen.to_global_id(local_id)
    }

    /// Finish the build and return the inner stream graph builder.
    fn finish(self) -> StreamGraphBuilder {
        assert_eq!(self.actor_id_gen.len, self.next_local_id);
        self.stream_graph_builder
    }
}

/// [`ActorGraphBuilder`] generates the proto for interconnected actors for a streaming pipeline.
pub struct ActorGraphBuilder {
    /// The pre-scheduled distribution for each fragment.
    // TODO: this is fake now and only the parallelism is used, we should also use the physical
    // distribution itself after scheduler refactoring.
    distributions: HashMap<GlobalFragmentId, Distribution>,

    /// The stream fragment graph.
    fragment_graph: CompleteStreamFragmentGraph,

    cluster_info: StreamingClusterInfo,
}

impl ActorGraphBuilder {
    /// Create a new actor graph builder with the given "complete" graph. Returns an error if the
    /// graph is failed to be scheduled.
    pub fn new(
        complete_graph: CompleteStreamFragmentGraph,
        cluster_info: StreamingClusterInfo,
        default_parallelism: Option<NonZeroUsize>,
    ) -> MetaResult<Self> {
        let distributions = schedule::Scheduler::new(
            cluster_info.parallel_units.values().cloned(),
            default_parallelism,
        )?
        .schedule(&complete_graph)?;

        // TODO: directly use the complete graph when building so that we can generalize the
        // processing logic for `Chain`s.
        let fragment_graph = complete_graph;

        Ok(Self {
            distributions,
            fragment_graph,
            cluster_info,
        })
    }

    /// Build a stream graph by duplicating each fragment as parallel actors.
    pub async fn generate_graph<S>(
        self,
        id_gen_manager: IdGeneratorManagerRef<S>,
        ctx: &mut CreateStreamingJobContext,
    ) -> MetaResult<(StreamGraph, ScheduledLocations)>
    where
        S: MetaStore,
    {
        let actor_len = self
            .distributions
            .values()
            .map(|d| d.parallelism())
            .sum::<usize>() as u64;
        let id_gen = GlobalActorIdGen::new(&id_gen_manager, actor_len).await?;

        // Generate actors of the streaming plan
        let (actor_graph, actor_locations) =
            self.build_actor_graph(id_gen, ctx)?.finish().build(&*ctx)?;

        let scheduled_location = {
            let actor_locations = actor_locations
                .into_iter()
                .map(|(id, p)| {
                    (
                        id.as_global_id(),
                        self.cluster_info.parallel_units[&p].clone(),
                    )
                })
                .collect();

            let worker_locations = self.cluster_info.worker_nodes;

            let actor_vnode_bitmaps = actor_graph
                .values()
                .flatten()
                .map(|actor| (actor.actor_id, actor.vnode_bitmap.clone()))
                .collect();

            ScheduledLocations {
                actor_locations,
                worker_locations,
                actor_vnode_bitmaps,
            }
        };

        // Serialize the graph
        let stream_graph = actor_graph
            .into_iter()
            .map(|(fragment_id, actors)| {
                let distribution = self.distributions[&fragment_id].clone();
                let fragment = self
                    .fragment_graph
                    .seal_fragment(fragment_id, actors, distribution);
                let fragment_id = fragment_id.as_global_id();
                (fragment_id, fragment)
            })
            .collect();

        Ok((stream_graph, scheduled_location))
    }

    /// Build actor graph from fragment graph using topological order. Setup dispatcher in actor and
    /// generate actors by their parallelism.
    fn build_actor_graph(
        &self,
        id_gen: GlobalActorIdGen,
        ctx: &mut CreateStreamingJobContext,
    ) -> MetaResult<BuildActorGraphState> {
        let mut state = BuildActorGraphState::new(id_gen);

        // Use topological sort to build the graph from downstream to upstream. (The first fragment
        // popped out from the heap will be the top-most node in plan, or the sink in stream graph.)
        for fragment_id in self.fragment_graph.topo_order()? {
            // Build the actors corresponding to the fragment
            self.build_actor_graph_fragment(fragment_id, &mut state, ctx)?;
        }

        Ok(state)
    }

    fn build_actor_graph_fragment(
        &self,
        fragment_id: GlobalFragmentId,
        state: &mut BuildActorGraphState,
        ctx: &mut CreateStreamingJobContext,
    ) -> MetaResult<()> {
        let current_fragment = self.fragment_graph.get_fragment(fragment_id);

        let (distribution, actor_ids) = match current_fragment {
            MyFragment::Building(current_fragment) => {
                let node = Arc::new(current_fragment.node.clone().unwrap());

                let distribution = self.distributions[&fragment_id].clone();

                let bitmaps = distribution.as_hash().map(|m| m.to_bitmaps());

                let actor_ids = distribution
                    .parallel_units()
                    .map(|parallel_unit_id| {
                        let actor_id = state.next_actor_id();
                        let vnode_bitmap = bitmaps.as_ref().map(|m| &m[&parallel_unit_id]).cloned();

                        state.stream_graph_builder.add_actor(
                            actor_id,
                            fragment_id,
                            parallel_unit_id,
                            vnode_bitmap,
                            node.clone(),
                        );

                        actor_id
                    })
                    .collect_vec();

                (distribution, actor_ids)
            }

            MyFragment::Existing(existing_fragment) => {
                let distribution = Distribution::from_fragment(&existing_fragment);

                let actor_ids = existing_fragment
                    .actors
                    .iter()
                    .map(|a| {
                        let actor_id = GlobalActorId::new(a.actor_id);
                        let parallel_unit_id = match &distribution {
                            Distribution::Singleton(parallel_unit_id) => *parallel_unit_id,
                            Distribution::Hash(mapping) => mapping
                                .get_matched(&Bitmap::from(a.get_vnode_bitmap().unwrap()))
                                .unwrap(),
                        };

                        state
                            .stream_graph_builder
                            .record_location(actor_id, parallel_unit_id);

                        actor_id
                    })
                    .collect_vec();

                (distribution, actor_ids)
            }
        };

        for (downstream_fragment_id, edge) in self.fragment_graph.get_downstreams(fragment_id) {
            let downstream_actors = state
                .fragment_actors
                .get(&downstream_fragment_id)
                .expect("downstream fragment not processed yet");

            let downstream_distribution = &self.distributions[&downstream_fragment_id];

            state.stream_graph_builder.add_link(
                Node {
                    fragment_id,
                    actor_ids: &actor_ids,
                    distribution: &distribution,
                },
                Node {
                    fragment_id: downstream_fragment_id,
                    actor_ids: downstream_actors,
                    distribution: downstream_distribution,
                },
                edge,
            );
        }

        state
            .fragment_actors
            .try_insert(fragment_id, actor_ids)
            .unwrap_or_else(|_| panic!("fragment {:?} is already processed", fragment_id));

        Ok(())
    }
}

/// The fragment in the building phase, including the [`StreamFragment`] from the frontend and
/// several additional helper fields.
#[derive(Debug, Clone)]
pub struct BuildingFragment {
    /// The fragment structure from the frontend, with the global fragment ID.
    inner: StreamFragment,

    /// A clone of the internal tables in this fragment.
    internal_tables: Vec<Table>,

    /// The ID of the job if it's materialized in this fragment.
    table_id: Option<u32>,
}

impl BuildingFragment {
    /// Create a new [`BuildingFragment`] from a [`StreamFragment`]. The global fragment ID and
    /// global table IDs will be correctly filled with the given `id` and `table_id_gen`.
    fn new(
        id: GlobalFragmentId,
        fragment: StreamFragment,
        job: &StreamingJob,
        table_id_gen: GlobalTableIdGen,
    ) -> Self {
        let mut fragment = StreamFragment {
            fragment_id: id.as_global_id(),
            ..fragment
        };
        let internal_tables = Self::fill_internal_tables(&mut fragment, job, table_id_gen);
        let table_id = Self::fill_job(&mut fragment, job).then(|| job.id());

        Self {
            inner: fragment,
            internal_tables,
            table_id,
        }
    }

    /// Fill the information of the internal tables in the fragment.
    fn fill_internal_tables(
        fragment: &mut StreamFragment,
        job: &StreamingJob,
        table_id_gen: GlobalTableIdGen,
    ) -> Vec<Table> {
        let fragment_id = fragment.fragment_id;
        let mut internal_tables = Vec::new();

        visit_internal_tables(fragment, |table, table_type_name| {
            table.id = table_id_gen.to_global_id(table.id).as_global_id();
            table.schema_id = job.schema_id();
            table.database_id = job.database_id();
            table.name = generate_internal_table_name_with_type(
                &job.name(),
                fragment_id,
                table.id,
                table_type_name,
            );
            table.fragment_id = fragment_id;

            // Record the internal table.
            internal_tables.push(table.clone());
        });

        internal_tables
    }

    /// Fill the information of the job in the fragment.
    fn fill_job(fragment: &mut StreamFragment, job: &StreamingJob) -> bool {
        let table_id = job.id();
        let fragment_id = fragment.fragment_id;
        let mut has_table = false;

        visit_fragment(fragment, |node_body| match node_body {
            NodeBody::Materialize(materialize_node) => {
                materialize_node.table_id = table_id;

                // Fill the ID of the `Table`.
                let table = materialize_node.table.as_mut().unwrap();
                table.id = table_id;
                table.database_id = job.database_id();
                table.schema_id = job.schema_id();
                table.fragment_id = fragment_id;

                has_table = true;
            }
            NodeBody::Sink(sink_node) => {
                sink_node.table_id = table_id;

                has_table = true;
            }
            NodeBody::Dml(dml_node) => {
                dml_node.table_id = table_id;
            }
            _ => {}
        });

        has_table
    }
}

impl Deref for BuildingFragment {
    type Target = StreamFragment;

    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
enum EdgeId {
    Internal {
        exchange_id: u64,
    },

    UpstreamExternal {
        upstream_table_id: u32,
        downstream_fragment_id: GlobalFragmentId,
    },
}

#[derive(Debug, Clone)]
struct StreamFragmentEdge {
    id: EdgeId,

    dispatch_strategy: DispatchStrategy,
}

impl StreamFragmentEdge {
    fn from_protobuf(edge: &StreamFragmentEdgeProto) -> Self {
        Self {
            id: EdgeId::Internal {
                exchange_id: edge.link_id,
            },
            dispatch_strategy: edge.get_dispatch_strategy().unwrap().clone(),
        }
    }
}

/// In-memory representation of a **Fragment** Graph, built from the [`StreamFragmentGraphProto`]
/// from the frontend.
#[derive(Default)]
pub struct StreamFragmentGraph {
    /// stores all the fragments in the graph.
    fragments: HashMap<GlobalFragmentId, BuildingFragment>,

    /// stores edges between fragments: upstream => downstream.
    downstreams: HashMap<GlobalFragmentId, HashMap<GlobalFragmentId, StreamFragmentEdge>>,

    /// stores edges between fragments: downstream -> upstream.
    upstreams: HashMap<GlobalFragmentId, HashMap<GlobalFragmentId, StreamFragmentEdge>>,

    /// Dependent relations of this job.
    dependent_relations: HashSet<TableId>,
}

impl StreamFragmentGraph {
    /// Create a new [`StreamFragmentGraph`] from the given [`StreamFragmentGraphProto`], with all
    /// global IDs correctly filled.
    pub async fn new<S: MetaStore>(
        proto: StreamFragmentGraphProto,
        id_gen: IdGeneratorManagerRef<S>,
        job: &StreamingJob,
    ) -> MetaResult<Self> {
        let fragment_id_gen =
            GlobalFragmentIdGen::new(&id_gen, proto.fragments.len() as u64).await?;
        let table_id_gen = GlobalTableIdGen::new(&id_gen, proto.table_ids_cnt as u64).await?;

        // Create nodes.
        let fragments: HashMap<_, _> = proto
            .fragments
            .into_iter()
            .map(|(id, fragment)| {
                let id = fragment_id_gen.to_global_id(id);
                let fragment = BuildingFragment::new(id, fragment, job, table_id_gen);
                (id, fragment)
            })
            .collect();

        assert_eq!(
            fragments
                .values()
                .map(|f| f.internal_tables.len() as u32)
                .sum::<u32>(),
            proto.table_ids_cnt
        );

        // Create edges.
        let mut downstreams = HashMap::new();
        let mut upstreams = HashMap::new();

        for edge in proto.edges {
            let upstream_id = fragment_id_gen.to_global_id(edge.upstream_id);
            let downstream_id = fragment_id_gen.to_global_id(edge.downstream_id);
            let edge = StreamFragmentEdge::from_protobuf(&edge);

            upstreams
                .entry(downstream_id)
                .or_insert_with(HashMap::new)
                .try_insert(upstream_id, edge.clone())
                .unwrap();
            downstreams
                .entry(upstream_id)
                .or_insert_with(HashMap::new)
                .try_insert(downstream_id, edge)
                .unwrap();
        }

        // Note: Here we directly use the field `dependent_table_ids` in the proto (resolved in
        // frontend), instead of visiting the graph ourselves. Note that for creating table with a
        // connector, the source itself is NOT INCLUDED in this list.
        let dependent_relations = proto
            .dependent_table_ids
            .iter()
            .map(TableId::from)
            .collect();

        Ok(Self {
            fragments,
            downstreams,
            upstreams,
            dependent_relations,
        })
    }

    /// Retrieve the internal tables map of the whole graph.
    pub fn internal_tables(&self) -> HashMap<u32, Table> {
        let mut tables = HashMap::new();
        for fragment in self.fragments.values() {
            for table in &fragment.internal_tables {
                tables
                    .try_insert(table.id, table.clone())
                    .unwrap_or_else(|_| panic!("duplicated table id `{}`", table.id));
            }
        }
        tables
    }

    /// Returns the fragment id where the table is materialized.
    pub fn table_fragment_id(&self) -> FragmentId {
        self.fragments
            .values()
            .filter(|b| b.table_id.is_some())
            .map(|b| b.fragment_id)
            .exactly_one()
            .expect("require exactly 1 materialize/sink node when creating the streaming job")
    }

    pub fn dependent_relations(&self) -> &HashSet<TableId> {
        &self.dependent_relations
    }

    fn get_downstreams(
        &self,
        fragment_id: GlobalFragmentId,
    ) -> &HashMap<GlobalFragmentId, StreamFragmentEdge> {
        self.downstreams.get(&fragment_id).unwrap_or(&EMPTY_HASHMAP)
    }

    fn get_upstreams(
        &self,
        fragment_id: GlobalFragmentId,
    ) -> &HashMap<GlobalFragmentId, StreamFragmentEdge> {
        self.upstreams.get(&fragment_id).unwrap_or(&EMPTY_HASHMAP)
    }
}

static EMPTY_HASHMAP: LazyLock<HashMap<GlobalFragmentId, StreamFragmentEdge>> =
    LazyLock::new(HashMap::new);

#[derive(Debug, Clone, EnumAsInner)]
enum MyFragment {
    Building(BuildingFragment),
    Existing(Fragment),
}

/// A wrapper of [`StreamFragmentGraph`] that contains the information of existing fragments, which
/// is connected to the graph's top-most or bottom-most fragments.
///
/// For example, if we're going to build a mview on an existing mview, the upstream fragment
/// containing the `Materialize` node will be included in this structure.
pub struct CompleteStreamFragmentGraph {
    /// The fragment graph of this streaming job.
    building_graph: StreamFragmentGraph,

    /// The required information of existing fragments.
    existing_fragments: HashMap<GlobalFragmentId, Fragment>,

    /// Extra edges between existing fragments and the building fragments.
    downstreams: HashMap<GlobalFragmentId, HashMap<GlobalFragmentId, StreamFragmentEdge>>,

    /// Extra edges between existing fragments and the building fragments.
    upstreams: HashMap<GlobalFragmentId, HashMap<GlobalFragmentId, StreamFragmentEdge>>,
}

impl CompleteStreamFragmentGraph {
    /// Create a new [`CompleteStreamFragmentGraph`] with empty existing fragments, i.e., there's no
    /// upstream mviews.
    #[cfg(test)]
    pub fn for_test(graph: StreamFragmentGraph) -> Self {
        Self {
            building_graph: graph,
            existing_fragments: Default::default(),
            downstreams: Default::default(),
            upstreams: Default::default(),
        }
    }

    /// Create a new [`CompleteStreamFragmentGraph`] for MV-on-MV. Returns an error if the upstream
    /// `Matererialize` is failed to resolve.
    pub fn new(
        graph: StreamFragmentGraph,
        upstream_mview_fragments: HashMap<TableId, Fragment>,
    ) -> MetaResult<Self> {
        let mut downstreams = HashMap::new();
        let mut upstreams = HashMap::new();

        for (&id, fragment) in &graph.fragments {
            for &upstream_table_id in &fragment.upstream_table_ids {
                let mview_fragment = upstream_mview_fragments
                    .get(&TableId::new(upstream_table_id))
                    .context("upstream materialized view fragment not found")?;
                let mview_id = GlobalFragmentId::new(mview_fragment.fragment_id);

                let edge = StreamFragmentEdge {
                    id: EdgeId::UpstreamExternal {
                        upstream_table_id,
                        downstream_fragment_id: id,
                    },
                    // We always use `NoShuffle` for the exchange between the upstream `Materialize`
                    // and the downstream `Chain` of the new materialized view.
                    dispatch_strategy: DispatchStrategy {
                        r#type: DispatcherType::NoShuffle as _,
                        ..Default::default()
                    },
                };

                downstreams
                    .entry(mview_id)
                    .or_insert_with(HashMap::new)
                    .try_insert(id, edge.clone())
                    .unwrap();
                upstreams
                    .entry(id)
                    .or_insert_with(HashMap::new)
                    .try_insert(mview_id, edge)
                    .unwrap();
            }
        }

        let existing_fragments = upstream_mview_fragments
            .into_values()
            .map(|f| (GlobalFragmentId::new(f.fragment_id), f))
            .collect();

        Ok(Self {
            building_graph: graph,
            existing_fragments,
            downstreams,
            upstreams,
        })
    }

    fn all_fragment_ids<'a>(&'a self) -> impl Iterator<Item = GlobalFragmentId> + 'a {
        self.building_graph
            .fragments
            .keys()
            .chain(self.existing_fragments.keys())
            .copied()
    }

    /// Returns the dispatcher types of all edges in the complete graph.
    fn all_edges<'a>(
        &'a self,
    ) -> impl Iterator<Item = (GlobalFragmentId, GlobalFragmentId, &'a StreamFragmentEdge)> + 'a
    {
        self.building_graph
            .downstreams
            .iter()
            .chain(self.downstreams.iter())
            .flat_map(|(&from, tos)| tos.iter().map(move |(&to, edge)| (from, to, edge)))
    }

    /// Returns the distribution of the existing fragments.
    fn existing_distribution(&self) -> HashMap<GlobalFragmentId, Distribution> {
        self.existing_fragments
            .iter()
            .map(|(&id, f)| (id, Distribution::from_fragment(f)))
            .collect()
    }

    /// Generate topological order of the fragments in this graph. Returns error if the graph is not
    /// a DAG and topological sort can not be done.
    ///
    /// The first fragment popped out from the heap will be the top-most node, or the
    /// `Sink`/`Materialize` in stream graph.
    fn topo_order(&self) -> MetaResult<Vec<GlobalFragmentId>> {
        let mut topo = Vec::new();
        let mut downstream_cnts = HashMap::new();

        // Iterate all fragments
        for fragment_id in self.all_fragment_ids() {
            // Count how many downstreams we have for a given fragment
            let downstream_cnt = self.get_downstreams(fragment_id).count();
            if downstream_cnt == 0 {
                topo.push(fragment_id);
            } else {
                downstream_cnts.insert(fragment_id, downstream_cnt);
            }
        }

        let mut i = 0;
        while let Some(&fragment_id) = topo.get(i) {
            i += 1;
            // Find if we can process more fragments
            for (upstream_id, _) in self.get_upstreams(fragment_id) {
                let downstream_cnt = downstream_cnts.get_mut(&upstream_id).unwrap();
                *downstream_cnt -= 1;
                if *downstream_cnt == 0 {
                    downstream_cnts.remove(&upstream_id);
                    topo.push(upstream_id);
                }
            }
        }

        if !downstream_cnts.is_empty() {
            // There are fragments that are not processed yet.
            bail!("graph is not a DAG");
        }

        Ok(topo)
    }

    /// Seal a [`StreamFragment`] from the graph into a [`Fragment`], which will be further used to
    /// build actors, schedule, and persist into meta store.
    fn seal_fragment(
        &self,
        id: GlobalFragmentId,
        actors: Vec<StreamActor>,
        distribution: Distribution,
    ) -> Fragment {
        let BuildingFragment {
            inner,
            internal_tables,
            table_id,
        } = self.get_fragment(id).into_building().unwrap();

        let distribution_type = if inner.is_singleton {
            FragmentDistributionType::Single
        } else {
            FragmentDistributionType::Hash
        } as i32;

        let state_table_ids = internal_tables
            .iter()
            .map(|t| t.id)
            .chain(table_id)
            .collect();

        let upstream_fragment_ids = self
            .get_upstreams(id)
            .map(|(id, _)| id.as_global_id())
            .collect();

        Fragment {
            fragment_id: inner.fragment_id,
            fragment_type_mask: inner.fragment_type_mask,
            distribution_type,
            actors,
            vnode_mapping: Some(distribution.into_mapping().to_protobuf()),
            state_table_ids,
            upstream_fragment_ids,
        }
    }

    fn get_fragment(&self, fragment_id: GlobalFragmentId) -> MyFragment {
        if let Some(fragment) = self.existing_fragments.get(&fragment_id) {
            MyFragment::Existing(fragment.clone())
        } else {
            MyFragment::Building(
                self.building_graph
                    .fragments
                    .get(&fragment_id)
                    .unwrap()
                    .clone(),
            )
        }
    }

    fn get_downstreams(
        &self,
        fragment_id: GlobalFragmentId,
    ) -> impl Iterator<Item = (GlobalFragmentId, &StreamFragmentEdge)> {
        self.building_graph
            .get_downstreams(fragment_id)
            .iter()
            .chain(self.downstreams.get(&fragment_id).into_iter().flatten())
            .map(|(&id, edge)| (id, edge))
    }

    fn get_upstreams(
        &self,
        fragment_id: GlobalFragmentId,
    ) -> impl Iterator<Item = (GlobalFragmentId, &StreamFragmentEdge)> {
        self.building_graph
            .get_upstreams(fragment_id)
            .iter()
            .chain(self.upstreams.get(&fragment_id).into_iter().flatten())
            .map(|(&id, edge)| (id, edge))
    }

    fn building_fragments(&self) -> &HashMap<GlobalFragmentId, BuildingFragment> {
        &self.building_graph.fragments
    }
}

/// A utility for visiting and mutating the [`NodeBody`] of the [`StreamNode`]s in a
/// [`StreamFragment`] recursively.
pub fn visit_fragment<F>(fragment: &mut StreamFragment, mut f: F)
where
    F: FnMut(&mut NodeBody),
{
    fn visit_inner<F>(stream_node: &mut StreamNode, f: &mut F)
    where
        F: FnMut(&mut NodeBody),
    {
        f(stream_node.node_body.as_mut().unwrap());
        for input in &mut stream_node.input {
            visit_inner(input, f);
        }
    }

    visit_inner(fragment.node.as_mut().unwrap(), &mut f)
}

/// Visit the internal tables of a [`StreamFragment`].
fn visit_internal_tables<F>(fragment: &mut StreamFragment, mut f: F)
where
    F: FnMut(&mut Table, &'static str),
{
    macro_rules! always {
        ($table:expr, $name:expr) => {{
            let table = $table
                .as_mut()
                .unwrap_or_else(|| panic!("internal table {} should always exist", $name));
            f(table, $name);
        }};
    }

    #[allow(unused_macros)]
    macro_rules! optional {
        ($table:expr, $name:expr) => {
            if let Some(table) = &mut $table {
                f(table, $name);
            }
        };
    }

    visit_fragment(fragment, |body| {
        match body {
            // Join
            NodeBody::HashJoin(node) => {
                // TODO: make the degree table optional
                always!(node.left_table, "HashJoinLeft");
                always!(node.left_degree_table, "HashJoinDegreeLeft");
                always!(node.right_table, "HashJoinRight");
                always!(node.right_degree_table, "HashJoinDegreeRight");
            }
            NodeBody::DynamicFilter(node) => {
                always!(node.left_table, "DynamicFilterLeft");
                always!(node.right_table, "DynamicFilterRight");
            }

            // Aggregation
            NodeBody::HashAgg(node) => {
                assert_eq!(node.agg_call_states.len(), node.agg_calls.len());
                always!(node.result_table, "HashAggResult");
                for state in &mut node.agg_call_states {
                    if let agg_call_state::Inner::MaterializedInputState(s) =
                        state.inner.as_mut().unwrap()
                    {
                        always!(s.table, "HashAgg");
                    }
                }
            }
            NodeBody::GlobalSimpleAgg(node) => {
                assert_eq!(node.agg_call_states.len(), node.agg_calls.len());
                always!(node.result_table, "GlobalSimpleAggResult");
                for state in &mut node.agg_call_states {
                    if let agg_call_state::Inner::MaterializedInputState(s) =
                        state.inner.as_mut().unwrap()
                    {
                        always!(s.table, "GlobalSimpleAgg");
                    }
                }
            }

            // Top-N
            NodeBody::AppendOnlyTopN(node) => {
                always!(node.table, "AppendOnlyTopN");
            }
            NodeBody::TopN(node) => {
                always!(node.table, "TopN");
            }
            NodeBody::GroupTopN(node) => {
                always!(node.table, "GroupTopN");
            }

            // Source
            NodeBody::Source(node) => {
                if let Some(source) = &mut node.source_inner {
                    always!(source.state_table, "Source");
                }
            }
            NodeBody::Now(node) => {
                always!(node.state_table, "Now");
            }

            // Shared arrangement
            NodeBody::Arrange(node) => {
                always!(node.table, "Arrange");
            }

            // Note: add internal tables for new nodes here.
            _ => {}
        }
    })
}
