// Copyright 2023 RisingWave Labs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::collections::hash_map::HashMap;
use std::collections::{BTreeMap, HashSet};
use std::ops::Deref;
use std::sync::{Arc, LazyLock};

use anyhow::Context;
use assert_matches::assert_matches;
use itertools::Itertools;
use risingwave_common::bail;
use risingwave_common::buffer::Bitmap;
use risingwave_common::catalog::{generate_internal_table_name_with_type, TableId};
use risingwave_common::hash::{ActorId, ActorMapping, ParallelUnitId, ParallelUnitMapping};
use risingwave_pb::catalog::Table;
use risingwave_pb::common::ParallelUnit;
use risingwave_pb::meta::table_fragments::fragment::FragmentDistributionType;
use risingwave_pb::meta::table_fragments::Fragment;
use risingwave_pb::stream_plan::stream_fragment_graph::{StreamFragment, StreamFragmentEdge};
use risingwave_pb::stream_plan::stream_node::NodeBody;
use risingwave_pb::stream_plan::{
    agg_call_state, DispatchStrategy, Dispatcher, DispatcherType, MergeNode, StreamActor,
    StreamFragmentGraph as StreamFragmentGraphProto, StreamNode,
};

use self::schedule::Distribution;
use super::CreateStreamingJobContext;
use crate::manager::{
    IdCategory, IdCategoryType, IdGeneratorManager, IdGeneratorManagerRef, StreamingJob,
};
use crate::model::FragmentId;
use crate::storage::MetaStore;
use crate::MetaResult;

mod schedule;

/// A wrapper to distinguish global ID generated by the [`IdGeneratorManager`] and the local ID from
/// the frontend.
#[derive(Clone, Copy, Debug, Hash, Eq, PartialEq, PartialOrd, Ord)]
struct GlobalId<const TYPE: IdCategoryType>(u32);

impl<const TYPE: IdCategoryType> GlobalId<TYPE> {
    pub const fn new(id: u32) -> Self {
        Self(id)
    }

    pub fn as_global_id(&self) -> u32 {
        self.0
    }
}

/// Utility for converting local IDs into pre-allocated global IDs by adding an `offset`.
///
/// This requires the local IDs exactly a permutation of the range `[0, len)`.
#[derive(Clone, Copy, Debug)]
struct GlobalIdGen<const TYPE: IdCategoryType> {
    offset: u32,
    len: u32,
}

impl<const TYPE: IdCategoryType> GlobalIdGen<TYPE> {
    /// Pre-allocate a range of IDs with the given `len` and return the generator.
    pub async fn new<S: MetaStore>(id_gen: &IdGeneratorManager<S>, len: u64) -> MetaResult<Self> {
        let offset = id_gen.generate_interval::<TYPE>(len).await?;
        Ok(Self {
            offset: offset as u32,
            len: len as u32,
        })
    }

    /// Convert local id to global id. Panics if `id >= len`.
    pub fn to_global_id(self, local_id: u32) -> GlobalId<TYPE> {
        assert!(
            local_id < self.len,
            "id {} is out of range (len: {})",
            local_id,
            self.len
        );
        GlobalId(local_id + self.offset)
    }
}

type GlobalFragmentId = GlobalId<{ IdCategory::Fragment }>;
type GlobalFragmentIdGen = GlobalIdGen<{ IdCategory::Fragment }>;

type GlobalTableIdGen = GlobalIdGen<{ IdCategory::Table }>;

type GlobalActorId = GlobalId<{ IdCategory::Actor }>;
type GlobalActorIdGen = GlobalIdGen<{ IdCategory::Actor }>;

/// A list of actors with order.
#[derive(Debug, Clone)]
struct OrderedActorLink(pub Vec<GlobalActorId>);

impl OrderedActorLink {
    pub fn as_global_ids(&self) -> Vec<u32> {
        self.0.iter().map(|x| x.as_global_id()).collect()
    }
}

#[derive(Debug)]
struct StreamActorUpstream {
    /// Upstream actors
    actors: OrderedActorLink,
    /// associate fragment id
    fragment_id: GlobalFragmentId,
}

type ExchangeId = u64;

/// [`StreamActorBuilder`] builds a stream actor in a stream DAG.
#[derive(Debug)]
struct StreamActorBuilder {
    /// actor id field
    actor_id: GlobalActorId,

    /// associated fragment id
    fragment_id: GlobalFragmentId,

    /// associated stream node
    nodes: Arc<StreamNode>,

    new_downstreams: HashMap<GlobalFragmentId, Dispatcher>,

    /// upstreams, exchange node operator_id -> upstream actor ids
    upstreams: HashMap<ExchangeId, StreamActorUpstream>,

    vnode_bitmap: Option<Bitmap>,
}

impl StreamActorBuilder {
    pub fn new(
        actor_id: GlobalActorId,
        fragment_id: GlobalFragmentId,
        vnode_bitmap: Option<Bitmap>,
        node: Arc<StreamNode>,
    ) -> Self {
        Self {
            actor_id,
            fragment_id,
            nodes: node,
            new_downstreams: HashMap::new(),
            upstreams: HashMap::new(),
            vnode_bitmap,
        }
    }

    pub fn fragment_id(&self) -> GlobalFragmentId {
        self.fragment_id
    }

    pub fn add_dispatcher_hash(
        &mut self,
        column_indices: &[u32],
        downstream_fragment_id: GlobalFragmentId,
        downstream_actors: &[GlobalActorId],
        downstream_actor_mapping: ActorMapping,
    ) {
        let dispatcher_id = downstream_fragment_id.as_global_id() as u64;

        let dispatcher = Dispatcher {
            r#type: DispatcherType::Hash as _,
            column_indices: column_indices.to_vec(),
            hash_mapping: Some(downstream_actor_mapping.to_protobuf()),
            dispatcher_id,
            downstream_actor_id: OrderedActorLink(downstream_actors.to_vec()).as_global_ids(), /* TODO */
        };

        self.new_downstreams
            .try_insert(downstream_fragment_id, dispatcher)
            .unwrap();
    }

    pub fn add_dispatcher_normal(
        &mut self,
        dispatcher_type: DispatcherType,
        downstream_fragment_id: GlobalFragmentId,
        downstream_actors: &[GlobalActorId],
    ) {
        let dispatcher_id = downstream_fragment_id.as_global_id() as u64;

        assert_ne!(dispatcher_type, DispatcherType::Hash);
        let dispatcher = Dispatcher {
            r#type: dispatcher_type as _,
            column_indices: Vec::new(),
            hash_mapping: None,
            dispatcher_id,
            downstream_actor_id: OrderedActorLink(downstream_actors.to_vec()).as_global_ids(), /* TODO */
        };

        self.new_downstreams
            .try_insert(downstream_fragment_id, dispatcher)
            .unwrap();
    }

    fn rewrite(&self) -> MetaResult<StreamNode> {
        self.rewrite_inner(&self.nodes, 0)
    }

    /// Build stream actor inside, two works will be done:
    /// 1. replace node's input with [`MergeNode`] if it is `ExchangeNode`, and swallow
    /// mergeNode's input.
    /// 2. ignore root node when it's `ExchangeNode`.
    /// 3. replace node's `ExchangeNode` input with [`MergeNode`] and resolve its upstream actor
    /// ids if it is a `ChainNode`.
    fn rewrite_inner(&self, stream_node: &StreamNode, depth: usize) -> MetaResult<StreamNode> {
        match stream_node.get_node_body()? {
            NodeBody::Exchange(exchange) => {
                assert!(depth > 0, "ExchangeNode should be eliminated from the top of the plan node when converting fragments to actors: {:#?}", stream_node);
                assert!(!stream_node.get_fields().is_empty());
                assert!(stream_node.input.is_empty());

                Ok(StreamNode {
                    node_body: Some(NodeBody::Merge(MergeNode {
                        upstream_actor_id: self.upstreams[&stream_node.get_operator_id()]
                            .actors
                            .as_global_ids(),
                        upstream_fragment_id: self.upstreams[&stream_node.get_operator_id()]
                            .fragment_id
                            .as_global_id(),
                        upstream_dispatcher_type: exchange.get_strategy()?.r#type,
                        fields: stream_node.get_fields().clone(),
                    })),
                    identity: "MergeExecutor".to_string(),
                    ..stream_node.clone()
                })
            }
            NodeBody::Chain(_) => Self::resolve_chain_node(stream_node),

            _ => {
                let mut new_stream_node = stream_node.clone();
                for (input, new_input) in
                    stream_node.input.iter().zip_eq(&mut new_stream_node.input)
                {
                    *new_input = self.rewrite_inner(input, depth + 1)?;
                }
                Ok(new_stream_node)
            }
        }
    }

    /// Resolve the chain node, only rewrite the schema of input `MergeNode`.
    fn resolve_chain_node(stream_node: &StreamNode) -> MetaResult<StreamNode> {
        let NodeBody::Chain(chain_node) = stream_node.get_node_body().unwrap() else {
            unreachable!()
        };
        let input = stream_node.get_input();
        assert_eq!(input.len(), 2);

        let merge_node = &input[0];
        assert_matches!(merge_node.node_body, Some(NodeBody::Merge(_)));
        let batch_plan_node = &input[1];
        assert_matches!(batch_plan_node.node_body, Some(NodeBody::BatchPlan(_)));

        let chain_input = vec![
            StreamNode {
                input: vec![],
                stream_key: merge_node.stream_key.clone(),
                node_body: Some(NodeBody::Merge(MergeNode {
                    upstream_actor_id: vec![],
                    upstream_fragment_id: 0,
                    upstream_dispatcher_type: DispatcherType::NoShuffle as _,
                    fields: chain_node.upstream_fields.clone(),
                })),
                fields: chain_node.upstream_fields.clone(),
                operator_id: merge_node.operator_id,
                identity: "MergeExecutor".to_string(),
                append_only: stream_node.append_only,
            },
            batch_plan_node.clone(),
        ];

        Ok(StreamNode {
            input: chain_input,
            stream_key: stream_node.stream_key.clone(),
            node_body: Some(NodeBody::Chain(chain_node.clone())),
            operator_id: stream_node.operator_id,
            identity: "ChainExecutor".to_string(),
            fields: chain_node.upstream_fields.clone(),
            append_only: stream_node.append_only,
        })
    }

    /// Build an actor after seal.
    pub fn build(self, ctx: &CreateStreamingJobContext) -> MetaResult<StreamActor> {
        let rewritten_nodes = self.rewrite()?;

        // TODO: store each upstream separately
        let upstream_actor_id = self
            .upstreams
            .into_values()
            .flat_map(|StreamActorUpstream { actors, .. }| actors.0)
            .map(|x| x.as_global_id())
            .collect();

        Ok(StreamActor {
            actor_id: self.actor_id.as_global_id(),
            fragment_id: self.fragment_id.as_global_id(),
            nodes: Some(rewritten_nodes),
            dispatcher: self.new_downstreams.into_values().collect(),
            upstream_actor_id,
            colocated_upstream_actor_id: None, // TODO: remove this
            vnode_bitmap: self.vnode_bitmap.map(|b| b.to_protobuf()),
            mview_definition: ctx.streaming_definition.clone(),
        })
    }
}

struct Node<'a> {
    fragment_id: GlobalFragmentId,
    actor_ids: &'a [GlobalActorId],
    distribution: &'a Distribution,
}

/// [`StreamGraphBuilder`] build a stream graph. It injects some information to achieve
/// dependencies. See `build_inner` for more details.
#[derive(Default)]
struct StreamGraphBuilder {
    actor_builders: BTreeMap<GlobalActorId, StreamActorBuilder>,

    locations: BTreeMap<GlobalActorId, ParallelUnitId>,
}

impl StreamGraphBuilder {
    /// Insert new generated actor.
    pub fn add_actor(
        &mut self,
        actor_id: GlobalActorId,
        fragment_id: GlobalFragmentId,
        parallel_unit_id: ParallelUnitId,
        vnode_bitmap: Option<Bitmap>,
        node: Arc<StreamNode>,
    ) {
        self.actor_builders
            .try_insert(
                actor_id,
                StreamActorBuilder::new(actor_id, fragment_id, vnode_bitmap, node),
            )
            .unwrap();

        self.locations
            .try_insert(actor_id, parallel_unit_id)
            .unwrap();
    }

    /// Add dependency between two connected node in the graph.
    pub fn add_link<'a>(
        &mut self,
        upstream: Node<'a>,
        downstream: Node<'a>,
        dispatch_strategy: DispatchStrategy,
        exchange_id: ExchangeId,
    ) {
        // // Since the frontend uses the exchange's operator ID as the `link_id` of the edge, if
        // // there're multiple downstreams of a fragment, we cannot ensure this is unique. So we
        // // concat the fragment IDs to a unique link ID.
        // let link_id = ((upstream.fragment_id.as_global_id() as u64) << 32)
        //     | downstream.fragment_id.as_global_id() as u64;

        let dt = dispatch_strategy.r#type();
        match dt {
            DispatcherType::NoShuffle => {
                for (upstream_id, downstream_id) in upstream
                    .actor_ids
                    .iter()
                    .zip_eq(downstream.actor_ids.iter())
                {
                    let upstream_location = self.locations[upstream_id];
                    let downstream_location = self.locations[downstream_id];
                    assert_eq!(upstream_location, downstream_location);

                    self.actor_builders
                        .get_mut(upstream_id)
                        .unwrap()
                        .add_dispatcher_normal(dt, downstream.fragment_id, &[*downstream_id]);

                    // TODO: refactor
                    self.actor_builders
                        .get_mut(downstream_id)
                        .unwrap()
                        .upstreams
                        .try_insert(
                            exchange_id,
                            StreamActorUpstream {
                                actors: OrderedActorLink(vec![*upstream_id]),
                                fragment_id: upstream.fragment_id,
                            },
                        )
                        .unwrap_or_else(|_| {
                            panic!(
                                "duplicated exchange input {} for no-shuffle actors {:?} -> {:?}",
                                exchange_id, upstream_id, downstream_id
                            )
                        });
                }
            }

            // Otherwise, make m * n links between actors.
            DispatcherType::Hash | DispatcherType::Broadcast | DispatcherType::Simple => {
                if let DispatcherType::Hash = dt {
                    let downstream_locations: HashMap<ParallelUnitId, ActorId> = downstream
                        .actor_ids
                        .iter()
                        .map(|&actor_id| (self.locations[&actor_id], actor_id.as_global_id()))
                        .collect();
                    let actor_mapping = downstream
                        .distribution
                        .as_hash()
                        .unwrap()
                        .to_actor(&downstream_locations);

                    for upstream_id in upstream.actor_ids {
                        self.actor_builders
                            .get_mut(upstream_id)
                            .unwrap()
                            .add_dispatcher_hash(
                                &dispatch_strategy.column_indices,
                                downstream.fragment_id,
                                downstream.actor_ids,
                                actor_mapping.clone(),
                            );
                    }
                } else {
                    for upstream_id in upstream.actor_ids {
                        self.actor_builders
                            .get_mut(upstream_id)
                            .unwrap()
                            .add_dispatcher_normal(
                                dt,
                                downstream.fragment_id,
                                downstream.actor_ids,
                            );
                    }
                }

                for downstream_id in downstream.actor_ids {
                    self.actor_builders
                        .get_mut(downstream_id)
                        .unwrap()
                        .upstreams
                        .try_insert(
                            exchange_id,
                            StreamActorUpstream {
                                actors: OrderedActorLink(upstream.actor_ids.to_vec()),
                                fragment_id: upstream.fragment_id,
                            },
                        )
                        .unwrap_or_else(|_| {
                            panic!(
                                "duplicated exchange input {} for actors {:?} -> {:?}",
                                exchange_id, upstream.actor_ids, downstream.actor_ids
                            )
                        });
                }
            }

            DispatcherType::Unspecified => unreachable!(),
        }
    }

    /// Build final stream DAG with dependencies with current actor builders.
    #[allow(clippy::type_complexity)]
    pub fn build(
        self,
        ctx: &CreateStreamingJobContext,
    ) -> MetaResult<HashMap<GlobalFragmentId, Vec<StreamActor>>> {
        let mut graph: HashMap<GlobalFragmentId, Vec<StreamActor>> = HashMap::new();

        for builder in self.actor_builders.into_values() {
            let fragment_id = builder.fragment_id();
            let actor = builder.build(ctx)?;
            graph.entry(fragment_id).or_default().push(actor);
        }

        Ok(graph)
    }
}

/// The mutable state when building actor graph.
struct BuildActorGraphState {
    /// The stream graph builder, to build streaming DAG.
    stream_graph_builder: StreamGraphBuilder,

    /// When converting fragment graph to actor graph, we need to know which actors belong to a
    /// fragment.
    fragment_actors: HashMap<GlobalFragmentId, Vec<GlobalActorId>>,

    /// The next local actor id to use.
    next_local_id: u32,

    /// The global actor id generator.
    actor_id_gen: GlobalActorIdGen,
}

impl BuildActorGraphState {
    /// Create an empty state with the given id generator.
    fn new(actor_id_gen: GlobalActorIdGen) -> Self {
        Self {
            stream_graph_builder: Default::default(),
            fragment_actors: Default::default(),
            next_local_id: 0,
            actor_id_gen,
        }
    }

    /// Get the next global actor id.
    fn next_actor_id(&mut self) -> GlobalActorId {
        let local_id = self.next_local_id;
        self.next_local_id += 1;

        self.actor_id_gen.to_global_id(local_id)
    }

    /// Finish the build and return the inner stream graph builder.
    fn finish(self) -> StreamGraphBuilder {
        assert_eq!(self.actor_id_gen.len, self.next_local_id);
        self.stream_graph_builder
    }
}

/// [`ActorGraphBuilder`] generates the proto for interconnected actors for a streaming pipeline.
pub struct ActorGraphBuilder {
    /// The pre-scheduled distribution for each fragment.
    // TODO: this is fake now and only the parallelism is used, we should also use the physical
    // distribution itself after scheduler refactoring.
    distributions: HashMap<GlobalFragmentId, Distribution>,

    /// The stream fragment graph.
    fragment_graph: StreamFragmentGraph,
}

impl ActorGraphBuilder {
    /// Create a new actor graph builder with the given "complete" graph. Returns an error if the
    /// graph is failed to be scheduled.
    pub fn new(
        complete_graph: CompleteStreamFragmentGraph,
        all_parallel_units: impl IntoIterator<Item = ParallelUnit>,
        default_parallelism: u32,
    ) -> MetaResult<Self> {
        let distributions =
            schedule::Scheduler::new(all_parallel_units, default_parallelism as usize)?
                .schedule(&complete_graph)?;

        // TODO: directly use the complete graph when building so that we can generalize the
        // processing logic for `Chain`s.
        let fragment_graph = complete_graph.into_inner();

        Ok(Self {
            distributions,
            fragment_graph,
        })
    }

    /// Build a stream graph by duplicating each fragment as parallel actors.
    pub async fn generate_graph<S>(
        &self,
        id_gen_manager: IdGeneratorManagerRef<S>,
        ctx: &mut CreateStreamingJobContext,
    ) -> MetaResult<BTreeMap<FragmentId, Fragment>>
    where
        S: MetaStore,
    {
        let actor_len = self
            .distributions
            .values()
            .map(|d| d.parallelism())
            .sum::<usize>() as u64;
        let id_gen = GlobalActorIdGen::new(&id_gen_manager, actor_len).await?;

        // Generate actors of the streaming plan
        let stream_graph = self.build_actor_graph(id_gen, ctx)?.finish().build(&*ctx)?;

        // Serialize the graph
        let stream_graph = stream_graph
            .into_iter()
            .map(|(fragment_id, actors)| {
                let fragment = self.fragment_graph.seal_fragment(fragment_id, actors);
                let fragment_id = fragment_id.as_global_id();
                (fragment_id, fragment)
            })
            .collect();

        Ok(stream_graph)
    }

    /// Build actor graph from fragment graph using topological order. Setup dispatcher in actor and
    /// generate actors by their parallelism.
    fn build_actor_graph(
        &self,
        id_gen: GlobalActorIdGen,
        ctx: &mut CreateStreamingJobContext,
    ) -> MetaResult<BuildActorGraphState> {
        let mut state = BuildActorGraphState::new(id_gen);

        // Use topological sort to build the graph from downstream to upstream. (The first fragment
        // popped out from the heap will be the top-most node in plan, or the sink in stream graph.)
        for fragment_id in self.fragment_graph.topo_order()? {
            // Build the actors corresponding to the fragment
            self.build_actor_graph_fragment(fragment_id, &mut state, ctx)?;
        }

        Ok(state)
    }

    fn build_actor_graph_fragment(
        &self,
        fragment_id: GlobalFragmentId,
        state: &mut BuildActorGraphState,
        ctx: &mut CreateStreamingJobContext,
    ) -> MetaResult<()> {
        let current_fragment = self
            .fragment_graph
            .get_fragment(fragment_id)
            .unwrap()
            .clone();

        // TODO: remove this after scheduler refactoring.
        let upstream_table_id = current_fragment
            .upstream_table_ids
            .iter()
            .at_most_one()
            .unwrap()
            .map(TableId::from);
        if let Some(upstream_table_id) = upstream_table_id {
            ctx.chain_fragment_upstream_table_map
                .insert(fragment_id.as_global_id(), upstream_table_id);
        }

        let node = Arc::new(current_fragment.node.unwrap());

        let distribution = &self.distributions[&fragment_id];

        let bitmaps = distribution.as_hash().map(|m| m.to_bitmaps());

        let actor_ids = distribution
            .parallel_units()
            .map(|parallel_unit_id| {
                let actor_id = state.next_actor_id();
                let vnode_bitmap = bitmaps.as_ref().map(|m| &m[&parallel_unit_id]).cloned();

                state.stream_graph_builder.add_actor(
                    actor_id,
                    fragment_id,
                    parallel_unit_id,
                    vnode_bitmap,
                    node.clone(),
                );
                actor_id
            })
            .collect_vec();

        for (&downstream_fragment_id, dispatch_edge) in
            self.fragment_graph.get_downstreams(fragment_id)
        {
            let downstream_actors = state
                .fragment_actors
                .get(&downstream_fragment_id)
                .expect("downstream fragment not processed yet");

            let downstream_distribution = &self.distributions[&downstream_fragment_id];

            state.stream_graph_builder.add_link(
                Node {
                    fragment_id,
                    actor_ids: &actor_ids,
                    distribution,
                },
                Node {
                    fragment_id: downstream_fragment_id,
                    actor_ids: &downstream_actors,
                    distribution: downstream_distribution,
                },
                dispatch_edge.get_dispatch_strategy().unwrap().clone(),
                dispatch_edge.link_id, // TODO
            );
        }

        state
            .fragment_actors
            .try_insert(fragment_id, actor_ids)
            .unwrap_or_else(|_| panic!("fragment {:?} is already processed", fragment_id));

        Ok(())
    }
}

/// The fragment in the building phase, including the [`StreamFragment`] from the frontend and
/// several additional helper fields.
#[derive(Debug, Clone)]
pub struct BuildingFragment {
    /// The fragment structure from the frontend, with the global fragment ID.
    inner: StreamFragment,

    /// A clone of the internal tables in this fragment.
    internal_tables: Vec<Table>,

    /// The ID of the job if it's materialized in this fragment.
    table_id: Option<u32>,
}

impl BuildingFragment {
    /// Create a new [`BuildingFragment`] from a [`StreamFragment`]. The global fragment ID and
    /// global table IDs will be correctly filled with the given `id` and `table_id_gen`.
    fn new(
        id: GlobalFragmentId,
        fragment: StreamFragment,
        job: &StreamingJob,
        table_id_gen: GlobalTableIdGen,
    ) -> Self {
        let mut fragment = StreamFragment {
            fragment_id: id.as_global_id(),
            ..fragment
        };
        let internal_tables = Self::fill_internal_tables(&mut fragment, job, table_id_gen);
        let table_id = Self::fill_job(&mut fragment, job).then(|| job.id());

        Self {
            inner: fragment,
            internal_tables,
            table_id,
        }
    }

    /// Fill the information of the internal tables in the fragment.
    fn fill_internal_tables(
        fragment: &mut StreamFragment,
        job: &StreamingJob,
        table_id_gen: GlobalTableIdGen,
    ) -> Vec<Table> {
        let fragment_id = fragment.fragment_id;
        let mut internal_tables = Vec::new();

        visit_internal_tables(fragment, |table, table_type_name| {
            table.id = table_id_gen.to_global_id(table.id).as_global_id();
            table.schema_id = job.schema_id();
            table.database_id = job.database_id();
            table.name = generate_internal_table_name_with_type(
                &job.name(),
                fragment_id,
                table.id,
                table_type_name,
            );
            table.fragment_id = fragment_id;

            // Record the internal table.
            internal_tables.push(table.clone());
        });

        internal_tables
    }

    /// Fill the information of the job in the fragment.
    fn fill_job(fragment: &mut StreamFragment, job: &StreamingJob) -> bool {
        let table_id = job.id();
        let fragment_id = fragment.fragment_id;
        let mut has_table = false;

        visit_fragment(fragment, |node_body| match node_body {
            NodeBody::Materialize(materialize_node) => {
                materialize_node.table_id = table_id;

                // Fill the ID of the `Table`.
                let table = materialize_node.table.as_mut().unwrap();
                table.id = table_id;
                table.database_id = job.database_id();
                table.schema_id = job.schema_id();
                table.fragment_id = fragment_id;

                has_table = true;
            }
            NodeBody::Sink(sink_node) => {
                sink_node.table_id = table_id;

                has_table = true;
            }
            NodeBody::Dml(dml_node) => {
                dml_node.table_id = table_id;
            }
            _ => {}
        });

        has_table
    }
}

impl Deref for BuildingFragment {
    type Target = StreamFragment;

    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

/// In-memory representation of a **Fragment** Graph, built from the [`StreamFragmentGraphProto`]
/// from the frontend.
#[derive(Default)]
pub struct StreamFragmentGraph {
    /// stores all the fragments in the graph.
    fragments: HashMap<GlobalFragmentId, BuildingFragment>,

    /// stores edges between fragments: upstream => downstream.
    downstreams: HashMap<GlobalFragmentId, HashMap<GlobalFragmentId, StreamFragmentEdge>>,

    /// stores edges between fragments: downstream -> upstream.
    upstreams: HashMap<GlobalFragmentId, HashMap<GlobalFragmentId, StreamFragmentEdge>>,

    /// Dependent relations of this job.
    dependent_relations: HashSet<TableId>,
}

impl StreamFragmentGraph {
    /// Create a new [`StreamFragmentGraph`] from the given [`StreamFragmentGraphProto`], with all
    /// global IDs correctly filled.
    pub async fn new<S: MetaStore>(
        proto: StreamFragmentGraphProto,
        id_gen: IdGeneratorManagerRef<S>,
        job: &StreamingJob,
    ) -> MetaResult<Self> {
        let fragment_id_gen =
            GlobalFragmentIdGen::new(&id_gen, proto.fragments.len() as u64).await?;
        let table_id_gen = GlobalTableIdGen::new(&id_gen, proto.table_ids_cnt as u64).await?;

        // Create nodes.
        let fragments: HashMap<_, _> = proto
            .fragments
            .into_iter()
            .map(|(id, fragment)| {
                let id = fragment_id_gen.to_global_id(id);
                let fragment = BuildingFragment::new(id, fragment, job, table_id_gen);
                (id, fragment)
            })
            .collect();

        assert_eq!(
            fragments
                .values()
                .map(|f| f.internal_tables.len() as u32)
                .sum::<u32>(),
            proto.table_ids_cnt
        );

        // Create edges.
        let mut downstreams = HashMap::new();
        let mut upstreams = HashMap::new();

        for edge in proto.edges {
            let upstream_id = fragment_id_gen.to_global_id(edge.upstream_id);
            let downstream_id = fragment_id_gen.to_global_id(edge.downstream_id);

            upstreams
                .entry(downstream_id)
                .or_insert_with(HashMap::new)
                .try_insert(
                    upstream_id,
                    StreamFragmentEdge {
                        upstream_id: upstream_id.as_global_id(),
                        downstream_id: downstream_id.as_global_id(),
                        ..edge.clone()
                    },
                )
                .unwrap();
            downstreams
                .entry(upstream_id)
                .or_insert_with(HashMap::new)
                .try_insert(
                    downstream_id,
                    StreamFragmentEdge {
                        upstream_id: upstream_id.as_global_id(),
                        downstream_id: downstream_id.as_global_id(),
                        ..edge
                    },
                )
                .unwrap();
        }

        // Note: Here we directly use the field `dependent_table_ids` in the proto (resolved in
        // frontend), instead of visiting the graph ourselves. Note that for creating table with a
        // connector, the source itself is NOT INCLUDED in this list.
        let dependent_relations = proto
            .dependent_table_ids
            .iter()
            .map(TableId::from)
            .collect();

        Ok(Self {
            fragments,
            downstreams,
            upstreams,
            dependent_relations,
        })
    }

    /// Generate topological order of the fragments in this graph. Returns error if the graph is not
    /// a DAG and topological sort can not be done.
    ///
    /// The first fragment popped out from the heap will be the top-most node, or the
    /// `Sink`/`Materialize` in stream graph.
    fn topo_order(&self) -> MetaResult<Vec<GlobalFragmentId>> {
        let mut topo = Vec::new();
        let mut downstream_cnts = HashMap::new();

        // Iterate all fragments
        for fragment_id in self.fragments.keys() {
            // Count how many downstreams we have for a given fragment
            let downstream_cnt = self.get_downstreams(*fragment_id).len();
            if downstream_cnt == 0 {
                topo.push(*fragment_id);
            } else {
                downstream_cnts.insert(*fragment_id, downstream_cnt);
            }
        }

        let mut i = 0;
        while let Some(&fragment_id) = topo.get(i) {
            i += 1;
            // Find if we can process more fragments
            for upstream_id in self.get_upstreams(fragment_id).keys() {
                let downstream_cnt = downstream_cnts.get_mut(upstream_id).unwrap();
                *downstream_cnt -= 1;
                if *downstream_cnt == 0 {
                    downstream_cnts.remove(upstream_id);
                    topo.push(*upstream_id);
                }
            }
        }

        if !downstream_cnts.is_empty() {
            // There are fragments that are not processed yet.
            bail!("graph is not a DAG");
        }

        Ok(topo)
    }

    /// Seal a [`StreamFragment`] from the graph into a [`Fragment`], which will be further used to
    /// build actors, schedule, and persist into meta store.
    fn seal_fragment(&self, id: GlobalFragmentId, actors: Vec<StreamActor>) -> Fragment {
        let BuildingFragment {
            inner,
            internal_tables,
            table_id,
        } = self.fragments.get(&id).unwrap().to_owned();

        let distribution_type = if inner.is_singleton {
            FragmentDistributionType::Single
        } else {
            FragmentDistributionType::Hash
        } as i32;

        let state_table_ids = internal_tables
            .iter()
            .map(|t| t.id)
            .chain(table_id)
            .collect();

        let upstream_fragment_ids = self
            .get_upstreams(id)
            .keys()
            .map(|id| id.as_global_id())
            .collect();

        Fragment {
            fragment_id: inner.fragment_id,
            fragment_type_mask: inner.fragment_type_mask,
            distribution_type,
            actors,
            // Will be filled in `Scheduler::schedule` later.
            vnode_mapping: None,
            state_table_ids,
            upstream_fragment_ids,
        }
    }

    /// Retrieve the internal tables map of the whole graph.
    pub fn internal_tables(&self) -> HashMap<u32, Table> {
        let mut tables = HashMap::new();
        for fragment in self.fragments.values() {
            for table in &fragment.internal_tables {
                tables
                    .try_insert(table.id, table.clone())
                    .unwrap_or_else(|_| panic!("duplicated table id `{}`", table.id));
            }
        }
        tables
    }

    /// Returns the fragment id where the table is materialized.
    pub fn table_fragment_id(&self) -> FragmentId {
        self.fragments
            .values()
            .filter(|b| b.table_id.is_some())
            .map(|b| b.fragment_id)
            .exactly_one()
            .expect("require exactly 1 materialize/sink node when creating the streaming job")
    }

    pub fn dependent_relations(&self) -> &HashSet<TableId> {
        &self.dependent_relations
    }

    fn get_fragment(&self, fragment_id: GlobalFragmentId) -> Option<&StreamFragment> {
        self.fragments.get(&fragment_id).map(|b| b.deref())
    }

    fn get_downstreams(
        &self,
        fragment_id: GlobalFragmentId,
    ) -> &HashMap<GlobalFragmentId, StreamFragmentEdge> {
        self.downstreams.get(&fragment_id).unwrap_or(&EMPTY_HASHMAP)
    }

    fn get_upstreams(
        &self,
        fragment_id: GlobalFragmentId,
    ) -> &HashMap<GlobalFragmentId, StreamFragmentEdge> {
        self.upstreams.get(&fragment_id).unwrap_or(&EMPTY_HASHMAP)
    }

    fn edges(
        &self,
    ) -> impl Iterator<Item = (GlobalFragmentId, GlobalFragmentId, &StreamFragmentEdge)> {
        self.downstreams
            .iter()
            .flat_map(|(&from, tos)| tos.iter().map(move |(&to, edge)| (from, to, edge)))
    }
}

static EMPTY_HASHMAP: LazyLock<HashMap<GlobalFragmentId, StreamFragmentEdge>> =
    LazyLock::new(HashMap::new);

/// A wrapper of [`StreamFragmentGraph`] that contains the information of existing fragments, which
/// is connected to the graph's top-most or bottom-most fragments.
///
/// For example, if we're going to build a mview on an existing mview, the upstream fragment
/// containing the `Materialize` node will be included in this structure.
pub struct CompleteStreamFragmentGraph {
    /// The fragment graph of this streaming job.
    graph: StreamFragmentGraph,

    /// The required information of existing fragments.
    existing_fragments: HashMap<GlobalFragmentId, Fragment>,

    /// Extra edges between existing fragments and the building fragments.
    downstreams: HashMap<GlobalFragmentId, HashMap<GlobalFragmentId, DispatcherType>>,

    /// Extra edges between existing fragments and the building fragments.
    #[expect(dead_code)]
    upstreams: HashMap<GlobalFragmentId, HashMap<GlobalFragmentId, DispatcherType>>,
}

impl CompleteStreamFragmentGraph {
    /// Create a new [`CompleteStreamFragmentGraph`] with empty existing fragments, i.e., there's no
    /// upstream mviews.
    #[cfg(test)]
    pub fn for_test(graph: StreamFragmentGraph) -> Self {
        Self {
            graph,
            existing_fragments: Default::default(),
            downstreams: Default::default(),
            upstreams: Default::default(),
        }
    }

    /// Create a new [`CompleteStreamFragmentGraph`] for MV-on-MV. Returns an error if the upstream
    /// `Matererialize` is failed to resolve.
    pub fn new(
        graph: StreamFragmentGraph,
        upstream_mview_fragments: HashMap<TableId, Fragment>,
    ) -> MetaResult<Self> {
        let mut downstreams = HashMap::new();
        let mut upstreams = HashMap::new();

        for (&id, fragment) in &graph.fragments {
            for &upstream_table_id in &fragment.upstream_table_ids {
                let mview_fragment = upstream_mview_fragments
                    .get(&TableId::new(upstream_table_id))
                    .context("upstream materialized view fragment not found")?;
                let mview_id = GlobalFragmentId::new(mview_fragment.fragment_id);

                // We always use `NoShuffle` for the exchange between the upstream `Materialize` and
                // the downstream `Chain` of the new materialized view.
                let dt = DispatcherType::NoShuffle;

                downstreams
                    .entry(mview_id)
                    .or_insert_with(HashMap::new)
                    .try_insert(id, dt)
                    .unwrap();
                upstreams
                    .entry(id)
                    .or_insert_with(HashMap::new)
                    .try_insert(mview_id, dt)
                    .unwrap();
            }
        }

        let existing_fragments = upstream_mview_fragments
            .into_values()
            .map(|f| (GlobalFragmentId::new(f.fragment_id), f))
            .collect();

        Ok(Self {
            graph,
            existing_fragments,
            downstreams,
            upstreams,
        })
    }

    /// Returns the dispatcher types of all edges in the complete graph.
    fn dispatch_edges(
        &self,
    ) -> impl Iterator<Item = (GlobalFragmentId, GlobalFragmentId, DispatcherType)> + '_ {
        self.graph
            .edges()
            .map(|(from, to, edge)| {
                let dt = edge.get_dispatch_strategy().unwrap().get_type().unwrap();
                (from, to, dt)
            })
            .chain(
                self.downstreams
                    .iter()
                    .flat_map(|(&from, tos)| tos.iter().map(move |(&to, &dt)| (from, to, dt))),
            )
    }

    /// Returns the distribution of the existing fragments.
    fn existing_distribution(&self) -> HashMap<GlobalFragmentId, Distribution> {
        self.existing_fragments
            .iter()
            .map(|(&id, f)| {
                let mapping = ParallelUnitMapping::from_protobuf(f.get_vnode_mapping().unwrap());
                let dist = match f.get_distribution_type().unwrap() {
                    FragmentDistributionType::Unspecified => unreachable!(),
                    FragmentDistributionType::Single => {
                        let parallel_unit = mapping.iter_unique().exactly_one().ok().unwrap();
                        Distribution::Singleton(parallel_unit)
                    }
                    FragmentDistributionType::Hash => Distribution::Hash(mapping),
                };
                (id, dist)
            })
            .collect()
    }

    /// Consumes this complete graph and returns the inner graph.
    // TODO: remove this after scheduler refactoring.
    pub fn into_inner(self) -> StreamFragmentGraph {
        self.graph
    }
}

/// A utility for visiting and mutating the [`NodeBody`] of the [`StreamNode`]s in a
/// [`StreamFragment`] recursively.
pub fn visit_fragment<F>(fragment: &mut StreamFragment, mut f: F)
where
    F: FnMut(&mut NodeBody),
{
    fn visit_inner<F>(stream_node: &mut StreamNode, f: &mut F)
    where
        F: FnMut(&mut NodeBody),
    {
        f(stream_node.node_body.as_mut().unwrap());
        for input in &mut stream_node.input {
            visit_inner(input, f);
        }
    }

    visit_inner(fragment.node.as_mut().unwrap(), &mut f)
}

/// Visit the internal tables of a [`StreamFragment`].
fn visit_internal_tables<F>(fragment: &mut StreamFragment, mut f: F)
where
    F: FnMut(&mut Table, &'static str),
{
    macro_rules! always {
        ($table:expr, $name:expr) => {{
            let table = $table
                .as_mut()
                .unwrap_or_else(|| panic!("internal table {} should always exist", $name));
            f(table, $name);
        }};
    }

    #[allow(unused_macros)]
    macro_rules! optional {
        ($table:expr, $name:expr) => {
            if let Some(table) = &mut $table {
                f(table, $name);
            }
        };
    }

    visit_fragment(fragment, |body| {
        match body {
            // Join
            NodeBody::HashJoin(node) => {
                // TODO: make the degree table optional
                always!(node.left_table, "HashJoinLeft");
                always!(node.left_degree_table, "HashJoinDegreeLeft");
                always!(node.right_table, "HashJoinRight");
                always!(node.right_degree_table, "HashJoinDegreeRight");
            }
            NodeBody::DynamicFilter(node) => {
                always!(node.left_table, "DynamicFilterLeft");
                always!(node.right_table, "DynamicFilterRight");
            }

            // Aggregation
            NodeBody::HashAgg(node) => {
                assert_eq!(node.agg_call_states.len(), node.agg_calls.len());
                always!(node.result_table, "HashAggResult");
                for state in &mut node.agg_call_states {
                    if let agg_call_state::Inner::MaterializedInputState(s) =
                        state.inner.as_mut().unwrap()
                    {
                        always!(s.table, "HashAgg");
                    }
                }
            }
            NodeBody::GlobalSimpleAgg(node) => {
                assert_eq!(node.agg_call_states.len(), node.agg_calls.len());
                always!(node.result_table, "GlobalSimpleAggResult");
                for state in &mut node.agg_call_states {
                    if let agg_call_state::Inner::MaterializedInputState(s) =
                        state.inner.as_mut().unwrap()
                    {
                        always!(s.table, "GlobalSimpleAgg");
                    }
                }
            }

            // Top-N
            NodeBody::AppendOnlyTopN(node) => {
                always!(node.table, "AppendOnlyTopN");
            }
            NodeBody::TopN(node) => {
                always!(node.table, "TopN");
            }
            NodeBody::GroupTopN(node) => {
                always!(node.table, "GroupTopN");
            }

            // Source
            NodeBody::Source(node) => {
                if let Some(source) = &mut node.source_inner {
                    always!(source.state_table, "Source");
                }
            }
            NodeBody::Now(node) => {
                always!(node.state_table, "Now");
            }

            // Shared arrangement
            NodeBody::Arrange(node) => {
                always!(node.table, "Arrange");
            }

            // Note: add internal tables for new nodes here.
            _ => {}
        }
    })
}
