[package]
name = "risingwave_error"
version.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1"
bytes = "1"
easy-ext = "1"
serde-error = "0.1"
thiserror = "1"
thiserror-ext = { workspace = true }
tonic = { workspace = true }

[lints]
workspace = true
