[server]
heartbeat_interval = 100

[batch]
chunk_size = 1024

[streaming]
chunk_size = 1024

[storage]
sstable_size = 268435456
block_size = 4096
bloom_false_positive = 0.1
data_directory = "hummock_001"
checksum_algo = "crc32c"
async_checkpoint_enabled = true