use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                Table::alter()
                    .table(Worker::Table)
                    .add_column(ColumnDef::new(Worker::StartedAt).big_integer().null())
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Worker::Table)
                    .add_column(ColumnDef::new(Worker::ResourceRwVersion).string().null())
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Worker::Table)
                    .add_column(
                        ColumnDef::new(Worker::ResourceTotalMemoryBytes)
                            .big_integer()
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Worker::Table)
                    .add_column(
                        ColumnDef::new(Worker::ResourceTotalCpuCores)
                            .big_integer()
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Worker::Table)
                    .add_column(ColumnDef::new(Worker::ResourceHostname).string().null())
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                Table::alter()
                    .table(Worker::Table)
                    .drop_column(Worker::ResourceHostname)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Worker::Table)
                    .drop_column(Worker::ResourceTotalCpuCores)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Worker::Table)
                    .drop_column(Worker::ResourceTotalMemoryBytes)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Worker::Table)
                    .drop_column(Worker::ResourceRwVersion)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Worker::Table)
                    .drop_column(Worker::StartedAt)
                    .to_owned(),
            )
            .await
    }
}

#[derive(DeriveIden)]
enum Worker {
    Table,
    StartedAt,
    ResourceRwVersion,
    ResourceTotalMemoryBytes,
    ResourceTotalCpuCores,
    ResourceHostname,
}
