FROM bitnami/spark:3.3

USER root

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean;

RUN rm -r /opt/bitnami/spark/jars && \
    curl https://ci-deps-dist.s3.amazonaws.com/spark-3.3.1-bin-hadoop3.tgz | \
    tar --extract --gzip --strip=1 --directory /opt/bitnami/spark/ spark-3.3.1-bin-hadoop3/jars/
RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.231/aws-java-sdk-bundle-1.12.231.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.231.jar
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar --output /opt/bitnami/spark/jars/hadoop-aws-3.3.1.jar
RUN curl https://repo1.maven.org/maven2/net/java/dev/jets3t/jets3t/0.9.4/jets3t-0.9.4.jar --output /opt/bitnami/spark/jars/jets3t-0.9.4.jar


COPY ./iceberg-compaction-sql/rewrite_small_files.py /opt/bitnami/spark
COPY ./iceberg-compaction-sql/remove_orpan_files.py /opt/bitnami/spark

# CMD [ "/bin/bash" ]

# COPY ./requirements_copy.txt /
# RUN pip install -r /requirements_copy.txt