[package]
name = "workspace-static-log-level"
version = "0.1.11"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Use a feature flag to control enable or not, otherwise `cargo build` will compile all features.
enabled = ["log", "tracing"]

[dependencies]
log = { version = "0.4", optional = true, features = ["release_max_level_info"] }
tracing = { version =  "0.1", optional = true, features = ["release_max_level_info"] }