name: Integration tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: run integration tests
        run: |
          cd connector_node
          mvn --batch-mode --update-snapshots clean package  -DskipTests=true
          sudo apt install postgresql postgresql-contrib libpq-dev
          sudo systemctl start postgresql || sudo pg_ctlcluster 12 main start
          # disable password encryption
          sudo -u postgres psql -c "CREATE ROLE test LOGIN SUPERUSER PASSWORD 'connector';"
          sudo -u postgres createdb test
          sudo -u postgres psql -d test -c "CREATE TABLE test (id serial PRIMARY KEY, name VARCHAR (50) NOT NULL);"

          cd assembly/target/
          tar xvf risingwave-connector-1.0.0.tar.gz
          sh ./start-service.sh &
          sleep 3
          cd ../../

          bash python-client/build-venv.sh
          cd python-client && bash gen-stub.sh

          if python3 integration_tests.py --file_sink; then
            echo "File sink test passed"
          else
            echo "File sink test failed"
            exit 1
          fi

          if python3 integration_tests.py --jdbc_sink; then
            echo "Jdbc sink test passed"
          else
            echo "Jdbc sink test failed"
            exit 1
          fi

          if python3 integration_tests.py --print_sink; then
            echo "Print sink test passed"
          else
            echo "Print sink test failed"
            exit 1
          fi

          echo "All tests passed"
