name: Deltalake sink test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: run deltalake sink test
        run: |
          mvn --batch-mode --update-snapshots clean package -DskipTests=true

          # set up minio for deltalake sink test
          wget https://dl.minio.io/server/minio/release/linux-amd64/minio
          chmod +x minio
          sudo ./minio server /tmp/minio &
          # wait for minio to start
          sleep 3
          wget https://dl.minio.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc config host add minio http://127.0.0.1:9000 minioadmin minioadmin
          ./mc mb minio/bucket

          # start connector-node service
          cd assembly/target/
          tar xvf risingwave-connector-1.0.0.tar.gz
          sh ./start-service.sh &
          sleep 3
          cd ../../

          bash python-client/build-venv.sh
          cd python-client && bash gen-stub.sh

          # run deltalake sink tests with pyspark
          pip install pyspark
          
          # test append-only mode
          python3 pyspark-util.py create_deltalake
          if python3 integration_tests.py --deltalake_sink; then
            python3 pyspark-util.py test_deltalake
            echo "Deltalake sink test passed"
          else
            echo "Deltalake sink test failed"
            exit 1
          fi

          # clean up minio
          cd ..
          ./mc rm -r -force minio/bucket
          ./mc rb minio/bucket