name: Label Triggered
on:
  pull_request:
    types:
      - labeled

jobs:
  add-comment-feature-telemetry:
    if: github.event.label.name == 'type/feature'
    runs-on: ubuntu-latest
    permissions:
      pull_request: write
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            :memo: **Telemetry Reminder**:
            If you're implementing this feature, please consider adding telemetry metrics to track its usage. This helps us understand how the feature is being used and improve it further.
            You can find the function `report_event` of telemetry reporting in the following files. Feel free to ask questions if you need any guidance!
            * `src/frontend/src/telemetry.rs`
            * `src/meta/src/telemetry.rs`
            * `src/stream/src/telemetry.rs`
            * `src/storage/compactor/src/telemetry.rs`
            Or calling `report_event_common` (`src/storage/compactor/src/telemetry.rs`) as if finding it hard to implement.
            :sparkles: Thank you for your contribution to RisingWave! :sparkles:
      