name: Typo checker
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v3

    - name: Check spelling of the entire repository
      uses: crate-ci/typos@v1.16.2

    - name: Check trailing whitespaces
      run: scripts/check/check-trailing-spaces.sh